/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Component.ComponentPath;
import model.tables.Model.ModelPath;
import model.tables.records.BrandRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Brand extends TableImpl<BrandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.brand</code>
     */
    public static final Brand BRAND = new Brand();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BrandRecord> getRecordType() {
        return BrandRecord.class;
    }

    /**
     * The column <code>public.brand.id</code>.
     */
    public final TableField<BrandRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.brand.label</code>.
     */
    public final TableField<BrandRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private Brand(Name alias, Table<BrandRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Brand(Name alias, Table<BrandRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.brand</code> table reference
     */
    public Brand(String alias) {
        this(DSL.name(alias), BRAND);
    }

    /**
     * Create an aliased <code>public.brand</code> table reference
     */
    public Brand(Name alias) {
        this(alias, BRAND);
    }

    /**
     * Create a <code>public.brand</code> table reference
     */
    public Brand() {
        this(DSL.name("brand"), null);
    }

    public <O extends Record> Brand(Table<O> path, ForeignKey<O, BrandRecord> childPath, InverseForeignKey<O, BrandRecord> parentPath) {
        super(path, childPath, parentPath, BRAND);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BrandPath extends Brand implements Path<BrandRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BrandPath(Table<O> path, ForeignKey<O, BrandRecord> childPath, InverseForeignKey<O, BrandRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BrandPath(Name alias, Table<BrandRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BrandPath as(String alias) {
            return new BrandPath(DSL.name(alias), this);
        }

        @Override
        public BrandPath as(Name alias) {
            return new BrandPath(alias, this);
        }

        @Override
        public BrandPath as(Table<?> alias) {
            return new BrandPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<BrandRecord, Integer> getIdentity() {
        return (Identity<BrandRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BrandRecord> getPrimaryKey() {
        return Keys.BRAND_PKEY;
    }

    @Override
    public List<UniqueKey<BrandRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.BRAND_LABEL_KEY);
    }

    private transient ComponentPath _component;

    /**
     * Get the implicit to-many join path to the <code>public.component</code>
     * table
     */
    public ComponentPath component() {
        if (_component == null)
            _component = new ComponentPath(this, null, Keys.COMPONENT__COMPONENT_ID_BRAND_FKEY.getInverseKey());

        return _component;
    }

    private transient ModelPath _model;

    /**
     * Get the implicit to-many join path to the <code>public.model</code> table
     */
    public ModelPath model() {
        if (_model == null)
            _model = new ModelPath(this, null, Keys.MODEL__MODEL_ID_BRAND_FKEY.getInverseKey());

        return _model;
    }

    @Override
    public List<Check<BrandRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("brand_label_check"), "(((label)::text <> ''::text))", true)
        );
    }

    @Override
    public Brand as(String alias) {
        return new Brand(DSL.name(alias), this);
    }

    @Override
    public Brand as(Name alias) {
        return new Brand(alias, this);
    }

    @Override
    public Brand as(Table<?> alias) {
        return new Brand(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Brand rename(String name) {
        return new Brand(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Brand rename(Name name) {
        return new Brand(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Brand rename(Table<?> name) {
        return new Brand(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Brand where(Condition condition) {
        return new Brand(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Brand where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Brand where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Brand where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Brand where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Brand where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Brand where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Brand where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Brand whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Brand whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
