/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Collection;

import model.Keys;
import model.Public;
import model.tables.Component.ComponentPath;
import model.tables.ReparationDetail.ReparationDetailPath;
import model.tables.records.ComponentCategoryRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ComponentCategory extends TableImpl<ComponentCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.component_category</code>
     */
    public static final ComponentCategory COMPONENT_CATEGORY = new ComponentCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ComponentCategoryRecord> getRecordType() {
        return ComponentCategoryRecord.class;
    }

    /**
     * The column <code>public.component_category.id</code>.
     */
    public final TableField<ComponentCategoryRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.component_category.label</code>.
     */
    public final TableField<ComponentCategoryRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private ComponentCategory(Name alias, Table<ComponentCategoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ComponentCategory(Name alias, Table<ComponentCategoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.component_category</code> table reference
     */
    public ComponentCategory(String alias) {
        this(DSL.name(alias), COMPONENT_CATEGORY);
    }

    /**
     * Create an aliased <code>public.component_category</code> table reference
     */
    public ComponentCategory(Name alias) {
        this(alias, COMPONENT_CATEGORY);
    }

    /**
     * Create a <code>public.component_category</code> table reference
     */
    public ComponentCategory() {
        this(DSL.name("component_category"), null);
    }

    public <O extends Record> ComponentCategory(Table<O> path, ForeignKey<O, ComponentCategoryRecord> childPath, InverseForeignKey<O, ComponentCategoryRecord> parentPath) {
        super(path, childPath, parentPath, COMPONENT_CATEGORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ComponentCategoryPath extends ComponentCategory implements Path<ComponentCategoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ComponentCategoryPath(Table<O> path, ForeignKey<O, ComponentCategoryRecord> childPath, InverseForeignKey<O, ComponentCategoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ComponentCategoryPath(Name alias, Table<ComponentCategoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ComponentCategoryPath as(String alias) {
            return new ComponentCategoryPath(DSL.name(alias), this);
        }

        @Override
        public ComponentCategoryPath as(Name alias) {
            return new ComponentCategoryPath(alias, this);
        }

        @Override
        public ComponentCategoryPath as(Table<?> alias) {
            return new ComponentCategoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ComponentCategoryRecord, Integer> getIdentity() {
        return (Identity<ComponentCategoryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ComponentCategoryRecord> getPrimaryKey() {
        return Keys.COMPONENT_CATEGORY_PKEY;
    }

    private transient ComponentPath _component;

    /**
     * Get the implicit to-many join path to the <code>public.component</code>
     * table
     */
    public ComponentPath component() {
        if (_component == null)
            _component = new ComponentPath(this, null, Keys.COMPONENT__COMPONENT_ID_COMPONENT_CATEGORY_FKEY.getInverseKey());

        return _component;
    }

    private transient ReparationDetailPath _reparationDetail;

    /**
     * Get the implicit to-many join path to the
     * <code>public.reparation_detail</code> table
     */
    public ReparationDetailPath reparationDetail() {
        if (_reparationDetail == null)
            _reparationDetail = new ReparationDetailPath(this, null, Keys.REPARATION_DETAIL__REPARATION_DETAIL_ID_COMPONENT_CATEGORY_FKEY.getInverseKey());

        return _reparationDetail;
    }

    @Override
    public ComponentCategory as(String alias) {
        return new ComponentCategory(DSL.name(alias), this);
    }

    @Override
    public ComponentCategory as(Name alias) {
        return new ComponentCategory(alias, this);
    }

    @Override
    public ComponentCategory as(Table<?> alias) {
        return new ComponentCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ComponentCategory rename(String name) {
        return new ComponentCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ComponentCategory rename(Name name) {
        return new ComponentCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ComponentCategory rename(Table<?> name) {
        return new ComponentCategory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComponentCategory where(Condition condition) {
        return new ComponentCategory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComponentCategory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComponentCategory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComponentCategory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ComponentCategory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ComponentCategory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ComponentCategory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ComponentCategory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComponentCategory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComponentCategory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
