/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Brand.BrandPath;
import model.tables.ComponentCategory.ComponentCategoryPath;
import model.tables.ModelCategory.ModelCategoryPath;
import model.tables.records.ComponentRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Component extends TableImpl<ComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.component</code>
     */
    public static final Component COMPONENT = new Component();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ComponentRecord> getRecordType() {
        return ComponentRecord.class;
    }

    /**
     * The column <code>public.component.id</code>.
     */
    public final TableField<ComponentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.component.serial_number</code>.
     */
    public final TableField<ComponentRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.component.id_component_category</code>.
     */
    public final TableField<ComponentRecord, Integer> ID_COMPONENT_CATEGORY = createField(DSL.name("id_component_category"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.component.id_model_category</code>.
     */
    public final TableField<ComponentRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.component.id_brand</code>.
     */
    public final TableField<ComponentRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.component.description</code>.
     */
    public final TableField<ComponentRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private Component(Name alias, Table<ComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Component(Name alias, Table<ComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.component</code> table reference
     */
    public Component(String alias) {
        this(DSL.name(alias), COMPONENT);
    }

    /**
     * Create an aliased <code>public.component</code> table reference
     */
    public Component(Name alias) {
        this(alias, COMPONENT);
    }

    /**
     * Create a <code>public.component</code> table reference
     */
    public Component() {
        this(DSL.name("component"), null);
    }

    public <O extends Record> Component(Table<O> path, ForeignKey<O, ComponentRecord> childPath, InverseForeignKey<O, ComponentRecord> parentPath) {
        super(path, childPath, parentPath, COMPONENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ComponentPath extends Component implements Path<ComponentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ComponentPath(Table<O> path, ForeignKey<O, ComponentRecord> childPath, InverseForeignKey<O, ComponentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ComponentPath(Name alias, Table<ComponentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ComponentPath as(String alias) {
            return new ComponentPath(DSL.name(alias), this);
        }

        @Override
        public ComponentPath as(Name alias) {
            return new ComponentPath(alias, this);
        }

        @Override
        public ComponentPath as(Table<?> alias) {
            return new ComponentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ComponentRecord, Integer> getIdentity() {
        return (Identity<ComponentRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ComponentRecord> getPrimaryKey() {
        return Keys.COMPONENT_PKEY;
    }

    @Override
    public List<ForeignKey<ComponentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.COMPONENT__COMPONENT_ID_BRAND_FKEY, Keys.COMPONENT__COMPONENT_ID_COMPONENT_CATEGORY_FKEY, Keys.COMPONENT__COMPONENT_ID_MODEL_CATEGORY_FKEY);
    }

    private transient BrandPath _brand;

    /**
     * Get the implicit join path to the <code>public.brand</code> table.
     */
    public BrandPath brand() {
        if (_brand == null)
            _brand = new BrandPath(this, Keys.COMPONENT__COMPONENT_ID_BRAND_FKEY, null);

        return _brand;
    }

    private transient ComponentCategoryPath _componentCategory;

    /**
     * Get the implicit join path to the <code>public.component_category</code>
     * table.
     */
    public ComponentCategoryPath componentCategory() {
        if (_componentCategory == null)
            _componentCategory = new ComponentCategoryPath(this, Keys.COMPONENT__COMPONENT_ID_COMPONENT_CATEGORY_FKEY, null);

        return _componentCategory;
    }

    private transient ModelCategoryPath _modelCategory;

    /**
     * Get the implicit join path to the <code>public.model_category</code>
     * table.
     */
    public ModelCategoryPath modelCategory() {
        if (_modelCategory == null)
            _modelCategory = new ModelCategoryPath(this, Keys.COMPONENT__COMPONENT_ID_MODEL_CATEGORY_FKEY, null);

        return _modelCategory;
    }

    @Override
    public Component as(String alias) {
        return new Component(DSL.name(alias), this);
    }

    @Override
    public Component as(Name alias) {
        return new Component(alias, this);
    }

    @Override
    public Component as(Table<?> alias) {
        return new Component(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Component rename(String name) {
        return new Component(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Component rename(Name name) {
        return new Component(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Component rename(Table<?> name) {
        return new Component(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Component where(Condition condition) {
        return new Component(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Component where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Component where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Component where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Component where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Component where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Component where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Component where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Component whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Component whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
