/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Gender.GenderPath;
import model.tables.Ticket.TicketPath;
import model.tables.records.EngineerRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Engineer extends TableImpl<EngineerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.engineer</code>
     */
    public static final Engineer ENGINEER = new Engineer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EngineerRecord> getRecordType() {
        return EngineerRecord.class;
    }

    /**
     * The column <code>public.engineer.id</code>.
     */
    public final TableField<EngineerRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.engineer.name</code>.
     */
    public final TableField<EngineerRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.engineer.telephone</code>.
     */
    public final TableField<EngineerRecord, String> TELEPHONE = createField(DSL.name("telephone"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.engineer.email</code>.
     */
    public final TableField<EngineerRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.engineer.address</code>.
     */
    public final TableField<EngineerRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.engineer.id_gender</code>.
     */
    public final TableField<EngineerRecord, Integer> ID_GENDER = createField(DSL.name("id_gender"), SQLDataType.INTEGER.nullable(false), this, "");

    private Engineer(Name alias, Table<EngineerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Engineer(Name alias, Table<EngineerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.engineer</code> table reference
     */
    public Engineer(String alias) {
        this(DSL.name(alias), ENGINEER);
    }

    /**
     * Create an aliased <code>public.engineer</code> table reference
     */
    public Engineer(Name alias) {
        this(alias, ENGINEER);
    }

    /**
     * Create a <code>public.engineer</code> table reference
     */
    public Engineer() {
        this(DSL.name("engineer"), null);
    }

    public <O extends Record> Engineer(Table<O> path, ForeignKey<O, EngineerRecord> childPath, InverseForeignKey<O, EngineerRecord> parentPath) {
        super(path, childPath, parentPath, ENGINEER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EngineerPath extends Engineer implements Path<EngineerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EngineerPath(Table<O> path, ForeignKey<O, EngineerRecord> childPath, InverseForeignKey<O, EngineerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EngineerPath(Name alias, Table<EngineerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EngineerPath as(String alias) {
            return new EngineerPath(DSL.name(alias), this);
        }

        @Override
        public EngineerPath as(Name alias) {
            return new EngineerPath(alias, this);
        }

        @Override
        public EngineerPath as(Table<?> alias) {
            return new EngineerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EngineerRecord, Integer> getIdentity() {
        return (Identity<EngineerRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<EngineerRecord> getPrimaryKey() {
        return Keys.ENGINEER_PKEY;
    }

    @Override
    public List<UniqueKey<EngineerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ENGINEER_NAME_KEY);
    }

    @Override
    public List<ForeignKey<EngineerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ENGINEER__ENGINEER_ID_GENDER_FKEY);
    }

    private transient GenderPath _gender;

    /**
     * Get the implicit join path to the <code>public.gender</code> table.
     */
    public GenderPath gender() {
        if (_gender == null)
            _gender = new GenderPath(this, Keys.ENGINEER__ENGINEER_ID_GENDER_FKEY, null);

        return _gender;
    }

    private transient TicketPath _ticket;

    /**
     * Get the implicit to-many join path to the <code>public.ticket</code>
     * table
     */
    public TicketPath ticket() {
        if (_ticket == null)
            _ticket = new TicketPath(this, null, Keys.TICKET__TICKET_ID_ENGINEER_FKEY.getInverseKey());

        return _ticket;
    }

    @Override
    public List<Check<EngineerRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("engineer_email_check"), "(((email)::text ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'::text))", true),
            Internal.createCheck(this, DSL.name("engineer_name_check"), "(((name)::text <> ''::text))", true),
            Internal.createCheck(this, DSL.name("engineer_telephone_check"), "(((telephone)::text ~ '^\\+?[0-9]{10,}$'::text))", true)
        );
    }

    @Override
    public Engineer as(String alias) {
        return new Engineer(DSL.name(alias), this);
    }

    @Override
    public Engineer as(Name alias) {
        return new Engineer(alias, this);
    }

    @Override
    public Engineer as(Table<?> alias) {
        return new Engineer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Engineer rename(String name) {
        return new Engineer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Engineer rename(Name name) {
        return new Engineer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Engineer rename(Table<?> name) {
        return new Engineer(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Engineer where(Condition condition) {
        return new Engineer(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Engineer where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Engineer where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Engineer where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Engineer where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Engineer where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Engineer where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Engineer where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Engineer whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Engineer whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
