/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Component.ComponentPath;
import model.tables.Model.ModelPath;
import model.tables.records.ModelCategoryRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ModelCategory extends TableImpl<ModelCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.model_category</code>
     */
    public static final ModelCategory MODEL_CATEGORY = new ModelCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModelCategoryRecord> getRecordType() {
        return ModelCategoryRecord.class;
    }

    /**
     * The column <code>public.model_category.id</code>.
     */
    public final TableField<ModelCategoryRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.model_category.label</code>.
     */
    public final TableField<ModelCategoryRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private ModelCategory(Name alias, Table<ModelCategoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ModelCategory(Name alias, Table<ModelCategoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.model_category</code> table reference
     */
    public ModelCategory(String alias) {
        this(DSL.name(alias), MODEL_CATEGORY);
    }

    /**
     * Create an aliased <code>public.model_category</code> table reference
     */
    public ModelCategory(Name alias) {
        this(alias, MODEL_CATEGORY);
    }

    /**
     * Create a <code>public.model_category</code> table reference
     */
    public ModelCategory() {
        this(DSL.name("model_category"), null);
    }

    public <O extends Record> ModelCategory(Table<O> path, ForeignKey<O, ModelCategoryRecord> childPath, InverseForeignKey<O, ModelCategoryRecord> parentPath) {
        super(path, childPath, parentPath, MODEL_CATEGORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ModelCategoryPath extends ModelCategory implements Path<ModelCategoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ModelCategoryPath(Table<O> path, ForeignKey<O, ModelCategoryRecord> childPath, InverseForeignKey<O, ModelCategoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ModelCategoryPath(Name alias, Table<ModelCategoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ModelCategoryPath as(String alias) {
            return new ModelCategoryPath(DSL.name(alias), this);
        }

        @Override
        public ModelCategoryPath as(Name alias) {
            return new ModelCategoryPath(alias, this);
        }

        @Override
        public ModelCategoryPath as(Table<?> alias) {
            return new ModelCategoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ModelCategoryRecord, Integer> getIdentity() {
        return (Identity<ModelCategoryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ModelCategoryRecord> getPrimaryKey() {
        return Keys.MODEL_CATEGORY_PKEY;
    }

    @Override
    public List<UniqueKey<ModelCategoryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MODEL_CATEGORY_LABEL_KEY);
    }

    private transient ComponentPath _component;

    /**
     * Get the implicit to-many join path to the <code>public.component</code>
     * table
     */
    public ComponentPath component() {
        if (_component == null)
            _component = new ComponentPath(this, null, Keys.COMPONENT__COMPONENT_ID_MODEL_CATEGORY_FKEY.getInverseKey());

        return _component;
    }

    private transient ModelPath _model;

    /**
     * Get the implicit to-many join path to the <code>public.model</code> table
     */
    public ModelPath model() {
        if (_model == null)
            _model = new ModelPath(this, null, Keys.MODEL__MODEL_ID_MODEL_CATEGORY_FKEY.getInverseKey());

        return _model;
    }

    @Override
    public List<Check<ModelCategoryRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("model_category_label_check"), "(((label)::text <> ''::text))", true)
        );
    }

    @Override
    public ModelCategory as(String alias) {
        return new ModelCategory(DSL.name(alias), this);
    }

    @Override
    public ModelCategory as(Name alias) {
        return new ModelCategory(alias, this);
    }

    @Override
    public ModelCategory as(Table<?> alias) {
        return new ModelCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ModelCategory rename(String name) {
        return new ModelCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ModelCategory rename(Name name) {
        return new ModelCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ModelCategory rename(Table<?> name) {
        return new ModelCategory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ModelCategory where(Condition condition) {
        return new ModelCategory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ModelCategory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ModelCategory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ModelCategory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ModelCategory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ModelCategory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ModelCategory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ModelCategory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ModelCategory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ModelCategory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
