/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Brand.BrandPath;
import model.tables.ModelCategory.ModelCategoryPath;
import model.tables.Reparation.ReparationPath;
import model.tables.records.ModelRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Model extends TableImpl<ModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.model</code>
     */
    public static final Model MODEL = new Model();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModelRecord> getRecordType() {
        return ModelRecord.class;
    }

    /**
     * The column <code>public.model.id</code>.
     */
    public final TableField<ModelRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.model.serial_number</code>.
     */
    public final TableField<ModelRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.model.id_model_category</code>.
     */
    public final TableField<ModelRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.model.id_brand</code>.
     */
    public final TableField<ModelRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.model.description</code>.
     */
    public final TableField<ModelRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private Model(Name alias, Table<ModelRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Model(Name alias, Table<ModelRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.model</code> table reference
     */
    public Model(String alias) {
        this(DSL.name(alias), MODEL);
    }

    /**
     * Create an aliased <code>public.model</code> table reference
     */
    public Model(Name alias) {
        this(alias, MODEL);
    }

    /**
     * Create a <code>public.model</code> table reference
     */
    public Model() {
        this(DSL.name("model"), null);
    }

    public <O extends Record> Model(Table<O> path, ForeignKey<O, ModelRecord> childPath, InverseForeignKey<O, ModelRecord> parentPath) {
        super(path, childPath, parentPath, MODEL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ModelPath extends Model implements Path<ModelRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ModelPath(Table<O> path, ForeignKey<O, ModelRecord> childPath, InverseForeignKey<O, ModelRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ModelPath(Name alias, Table<ModelRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ModelPath as(String alias) {
            return new ModelPath(DSL.name(alias), this);
        }

        @Override
        public ModelPath as(Name alias) {
            return new ModelPath(alias, this);
        }

        @Override
        public ModelPath as(Table<?> alias) {
            return new ModelPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ModelRecord, Integer> getIdentity() {
        return (Identity<ModelRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ModelRecord> getPrimaryKey() {
        return Keys.MODEL_PKEY;
    }

    @Override
    public List<ForeignKey<ModelRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MODEL__MODEL_ID_BRAND_FKEY, Keys.MODEL__MODEL_ID_MODEL_CATEGORY_FKEY);
    }

    private transient BrandPath _brand;

    /**
     * Get the implicit join path to the <code>public.brand</code> table.
     */
    public BrandPath brand() {
        if (_brand == null)
            _brand = new BrandPath(this, Keys.MODEL__MODEL_ID_BRAND_FKEY, null);

        return _brand;
    }

    private transient ModelCategoryPath _modelCategory;

    /**
     * Get the implicit join path to the <code>public.model_category</code>
     * table.
     */
    public ModelCategoryPath modelCategory() {
        if (_modelCategory == null)
            _modelCategory = new ModelCategoryPath(this, Keys.MODEL__MODEL_ID_MODEL_CATEGORY_FKEY, null);

        return _modelCategory;
    }

    private transient ReparationPath _reparation;

    /**
     * Get the implicit to-many join path to the <code>public.reparation</code>
     * table
     */
    public ReparationPath reparation() {
        if (_reparation == null)
            _reparation = new ReparationPath(this, null, Keys.REPARATION__REPARATION_ID_MODEL_FKEY.getInverseKey());

        return _reparation;
    }

    @Override
    public Model as(String alias) {
        return new Model(DSL.name(alias), this);
    }

    @Override
    public Model as(Name alias) {
        return new Model(alias, this);
    }

    @Override
    public Model as(Table<?> alias) {
        return new Model(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Model rename(String name) {
        return new Model(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Model rename(Name name) {
        return new Model(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Model rename(Table<?> name) {
        return new Model(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model where(Condition condition) {
        return new Model(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Model where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Model where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Model where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Model where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
