/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Ticket.TicketPath;
import model.tables.TicketState.TicketStatePath;
import model.tables.records.MvtTicketStateRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MvtTicketState extends TableImpl<MvtTicketStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mvt_ticket_state</code>
     */
    public static final MvtTicketState MVT_TICKET_STATE = new MvtTicketState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MvtTicketStateRecord> getRecordType() {
        return MvtTicketStateRecord.class;
    }

    /**
     * The column <code>public.mvt_ticket_state.id</code>.
     */
    public final TableField<MvtTicketStateRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mvt_ticket_state.datetime</code>.
     */
    public final TableField<MvtTicketStateRecord, LocalDateTime> DATETIME = createField(DSL.name("datetime"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.mvt_ticket_state.id_ticket</code>.
     */
    public final TableField<MvtTicketStateRecord, Integer> ID_TICKET = createField(DSL.name("id_ticket"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.mvt_ticket_state.id_ticket_state</code>.
     */
    public final TableField<MvtTicketStateRecord, Integer> ID_TICKET_STATE = createField(DSL.name("id_ticket_state"), SQLDataType.INTEGER.nullable(false), this, "");

    private MvtTicketState(Name alias, Table<MvtTicketStateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MvtTicketState(Name alias, Table<MvtTicketStateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mvt_ticket_state</code> table reference
     */
    public MvtTicketState(String alias) {
        this(DSL.name(alias), MVT_TICKET_STATE);
    }

    /**
     * Create an aliased <code>public.mvt_ticket_state</code> table reference
     */
    public MvtTicketState(Name alias) {
        this(alias, MVT_TICKET_STATE);
    }

    /**
     * Create a <code>public.mvt_ticket_state</code> table reference
     */
    public MvtTicketState() {
        this(DSL.name("mvt_ticket_state"), null);
    }

    public <O extends Record> MvtTicketState(Table<O> path, ForeignKey<O, MvtTicketStateRecord> childPath, InverseForeignKey<O, MvtTicketStateRecord> parentPath) {
        super(path, childPath, parentPath, MVT_TICKET_STATE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MvtTicketStatePath extends MvtTicketState implements Path<MvtTicketStateRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MvtTicketStatePath(Table<O> path, ForeignKey<O, MvtTicketStateRecord> childPath, InverseForeignKey<O, MvtTicketStateRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MvtTicketStatePath(Name alias, Table<MvtTicketStateRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MvtTicketStatePath as(String alias) {
            return new MvtTicketStatePath(DSL.name(alias), this);
        }

        @Override
        public MvtTicketStatePath as(Name alias) {
            return new MvtTicketStatePath(alias, this);
        }

        @Override
        public MvtTicketStatePath as(Table<?> alias) {
            return new MvtTicketStatePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MvtTicketStateRecord, Integer> getIdentity() {
        return (Identity<MvtTicketStateRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MvtTicketStateRecord> getPrimaryKey() {
        return Keys.MVT_TICKET_STATE_PKEY;
    }

    @Override
    public List<UniqueKey<MvtTicketStateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MVT_TICKET_STATE_ID_TICKET_ID_TICKET_STATE_KEY);
    }

    @Override
    public List<ForeignKey<MvtTicketStateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MVT_TICKET_STATE__MVT_TICKET_STATE_ID_TICKET_FKEY, Keys.MVT_TICKET_STATE__MVT_TICKET_STATE_ID_TICKET_STATE_FKEY);
    }

    private transient TicketPath _ticket;

    /**
     * Get the implicit join path to the <code>public.ticket</code> table.
     */
    public TicketPath ticket() {
        if (_ticket == null)
            _ticket = new TicketPath(this, Keys.MVT_TICKET_STATE__MVT_TICKET_STATE_ID_TICKET_FKEY, null);

        return _ticket;
    }

    private transient TicketStatePath _ticketState;

    /**
     * Get the implicit join path to the <code>public.ticket_state</code> table.
     */
    public TicketStatePath ticketState() {
        if (_ticketState == null)
            _ticketState = new TicketStatePath(this, Keys.MVT_TICKET_STATE__MVT_TICKET_STATE_ID_TICKET_STATE_FKEY, null);

        return _ticketState;
    }

    @Override
    public MvtTicketState as(String alias) {
        return new MvtTicketState(DSL.name(alias), this);
    }

    @Override
    public MvtTicketState as(Name alias) {
        return new MvtTicketState(alias, this);
    }

    @Override
    public MvtTicketState as(Table<?> alias) {
        return new MvtTicketState(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MvtTicketState rename(String name) {
        return new MvtTicketState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MvtTicketState rename(Name name) {
        return new MvtTicketState(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MvtTicketState rename(Table<?> name) {
        return new MvtTicketState(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MvtTicketState where(Condition condition) {
        return new MvtTicketState(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MvtTicketState where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MvtTicketState where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MvtTicketState where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MvtTicketState where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MvtTicketState where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MvtTicketState where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MvtTicketState where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MvtTicketState whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MvtTicketState whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
