/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Component.ComponentPath;
import model.tables.records.RecommendationComponentRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecommendationComponent extends TableImpl<RecommendationComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.recommendation_component</code>
     */
    public static final RecommendationComponent RECOMMENDATION_COMPONENT = new RecommendationComponent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecommendationComponentRecord> getRecordType() {
        return RecommendationComponentRecord.class;
    }

    /**
     * The column <code>public.recommendation_component.id</code>.
     */
    public final TableField<RecommendationComponentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.recommendation_component.id_component</code>.
     */
    public final TableField<RecommendationComponentRecord, Integer> ID_COMPONENT = createField(DSL.name("id_component"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.recommendation_component.date_start</code>.
     */
    public final TableField<RecommendationComponentRecord, LocalDate> DATE_START = createField(DSL.name("date_start"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.recommendation_component.date_end</code>.
     */
    public final TableField<RecommendationComponentRecord, LocalDate> DATE_END = createField(DSL.name("date_end"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private RecommendationComponent(Name alias, Table<RecommendationComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RecommendationComponent(Name alias, Table<RecommendationComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.recommendation_component</code> table
     * reference
     */
    public RecommendationComponent(String alias) {
        this(DSL.name(alias), RECOMMENDATION_COMPONENT);
    }

    /**
     * Create an aliased <code>public.recommendation_component</code> table
     * reference
     */
    public RecommendationComponent(Name alias) {
        this(alias, RECOMMENDATION_COMPONENT);
    }

    /**
     * Create a <code>public.recommendation_component</code> table reference
     */
    public RecommendationComponent() {
        this(DSL.name("recommendation_component"), null);
    }

    public <O extends Record> RecommendationComponent(Table<O> path, ForeignKey<O, RecommendationComponentRecord> childPath, InverseForeignKey<O, RecommendationComponentRecord> parentPath) {
        super(path, childPath, parentPath, RECOMMENDATION_COMPONENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RecommendationComponentPath extends RecommendationComponent implements Path<RecommendationComponentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RecommendationComponentPath(Table<O> path, ForeignKey<O, RecommendationComponentRecord> childPath, InverseForeignKey<O, RecommendationComponentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RecommendationComponentPath(Name alias, Table<RecommendationComponentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RecommendationComponentPath as(String alias) {
            return new RecommendationComponentPath(DSL.name(alias), this);
        }

        @Override
        public RecommendationComponentPath as(Name alias) {
            return new RecommendationComponentPath(alias, this);
        }

        @Override
        public RecommendationComponentPath as(Table<?> alias) {
            return new RecommendationComponentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RecommendationComponentRecord, Integer> getIdentity() {
        return (Identity<RecommendationComponentRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RecommendationComponentRecord> getPrimaryKey() {
        return Keys.RECOMMENDATION_COMPONENT_PKEY;
    }

    @Override
    public List<ForeignKey<RecommendationComponentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RECOMMENDATION_COMPONENT__RECOMMENDATION_COMPONENT_ID_COMPONENT_FKEY);
    }

    private transient ComponentPath _component;

    /**
     * Get the implicit join path to the <code>public.component</code> table.
     */
    public ComponentPath component() {
        if (_component == null)
            _component = new ComponentPath(this, Keys.RECOMMENDATION_COMPONENT__RECOMMENDATION_COMPONENT_ID_COMPONENT_FKEY, null);

        return _component;
    }

    @Override
    public RecommendationComponent as(String alias) {
        return new RecommendationComponent(DSL.name(alias), this);
    }

    @Override
    public RecommendationComponent as(Name alias) {
        return new RecommendationComponent(alias, this);
    }

    @Override
    public RecommendationComponent as(Table<?> alias) {
        return new RecommendationComponent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RecommendationComponent rename(String name) {
        return new RecommendationComponent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecommendationComponent rename(Name name) {
        return new RecommendationComponent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecommendationComponent rename(Table<?> name) {
        return new RecommendationComponent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecommendationComponent where(Condition condition) {
        return new RecommendationComponent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecommendationComponent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecommendationComponent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecommendationComponent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecommendationComponent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecommendationComponent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecommendationComponent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecommendationComponent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecommendationComponent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecommendationComponent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
