/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Customer.CustomerPath;
import model.tables.records.ReparationFeedbackRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReparationFeedback extends TableImpl<ReparationFeedbackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.reparation_feedback</code>
     */
    public static final ReparationFeedback REPARATION_FEEDBACK = new ReparationFeedback();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReparationFeedbackRecord> getRecordType() {
        return ReparationFeedbackRecord.class;
    }

    /**
     * The column <code>public.reparation_feedback.id</code>.
     */
    public final TableField<ReparationFeedbackRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.reparation_feedback.date</code>.
     */
    public final TableField<ReparationFeedbackRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.reparation_feedback.id_customer</code>.
     */
    public final TableField<ReparationFeedbackRecord, Integer> ID_CUSTOMER = createField(DSL.name("id_customer"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.reparation_feedback.id_reparation</code>.
     */
    public final TableField<ReparationFeedbackRecord, Integer> ID_REPARATION = createField(DSL.name("id_reparation"), SQLDataType.INTEGER.nullable(false), this, "");

    private ReparationFeedback(Name alias, Table<ReparationFeedbackRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReparationFeedback(Name alias, Table<ReparationFeedbackRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.reparation_feedback</code> table reference
     */
    public ReparationFeedback(String alias) {
        this(DSL.name(alias), REPARATION_FEEDBACK);
    }

    /**
     * Create an aliased <code>public.reparation_feedback</code> table reference
     */
    public ReparationFeedback(Name alias) {
        this(alias, REPARATION_FEEDBACK);
    }

    /**
     * Create a <code>public.reparation_feedback</code> table reference
     */
    public ReparationFeedback() {
        this(DSL.name("reparation_feedback"), null);
    }

    public <O extends Record> ReparationFeedback(Table<O> path, ForeignKey<O, ReparationFeedbackRecord> childPath, InverseForeignKey<O, ReparationFeedbackRecord> parentPath) {
        super(path, childPath, parentPath, REPARATION_FEEDBACK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReparationFeedbackPath extends ReparationFeedback implements Path<ReparationFeedbackRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReparationFeedbackPath(Table<O> path, ForeignKey<O, ReparationFeedbackRecord> childPath, InverseForeignKey<O, ReparationFeedbackRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReparationFeedbackPath(Name alias, Table<ReparationFeedbackRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReparationFeedbackPath as(String alias) {
            return new ReparationFeedbackPath(DSL.name(alias), this);
        }

        @Override
        public ReparationFeedbackPath as(Name alias) {
            return new ReparationFeedbackPath(alias, this);
        }

        @Override
        public ReparationFeedbackPath as(Table<?> alias) {
            return new ReparationFeedbackPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ReparationFeedbackRecord, Integer> getIdentity() {
        return (Identity<ReparationFeedbackRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReparationFeedbackRecord> getPrimaryKey() {
        return Keys.REPARATION_FEEDBACK_PKEY;
    }

    @Override
    public List<ForeignKey<ReparationFeedbackRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPARATION_FEEDBACK__REPARATION_FEEDBACK_ID_CUSTOMER_FKEY);
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit join path to the <code>public.customer</code> table.
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, Keys.REPARATION_FEEDBACK__REPARATION_FEEDBACK_ID_CUSTOMER_FKEY, null);

        return _customer;
    }

    @Override
    public ReparationFeedback as(String alias) {
        return new ReparationFeedback(DSL.name(alias), this);
    }

    @Override
    public ReparationFeedback as(Name alias) {
        return new ReparationFeedback(alias, this);
    }

    @Override
    public ReparationFeedback as(Table<?> alias) {
        return new ReparationFeedback(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReparationFeedback rename(String name) {
        return new ReparationFeedback(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReparationFeedback rename(Name name) {
        return new ReparationFeedback(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReparationFeedback rename(Table<?> name) {
        return new ReparationFeedback(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReparationFeedback where(Condition condition) {
        return new ReparationFeedback(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReparationFeedback where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReparationFeedback where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReparationFeedback where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReparationFeedback where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReparationFeedback where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReparationFeedback where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReparationFeedback where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReparationFeedback whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReparationFeedback whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
