/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Engineer.EngineerPath;
import model.tables.Model.ModelPath;
import model.tables.ReparationDetail.ReparationDetailPath;
import model.tables.ReparationFeedback.ReparationFeedbackPath;
import model.tables.records.ReparationRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Reparation extends TableImpl<ReparationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.reparation</code>
     */
    public static final Reparation REPARATION = new Reparation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReparationRecord> getRecordType() {
        return ReparationRecord.class;
    }

    /**
     * The column <code>public.reparation.id</code>.
     */
    public final TableField<ReparationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.reparation.date</code>.
     */
    public final TableField<ReparationRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.reparation.price</code>.
     */
    public final TableField<ReparationRecord, Double> PRICE = createField(DSL.name("price"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.reparation.id_model</code>.
     */
    public final TableField<ReparationRecord, Integer> ID_MODEL = createField(DSL.name("id_model"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.reparation.id_engineer</code>.
     */
    public final TableField<ReparationRecord, Integer> ID_ENGINEER = createField(DSL.name("id_engineer"), SQLDataType.INTEGER.nullable(false), this, "");

    private Reparation(Name alias, Table<ReparationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Reparation(Name alias, Table<ReparationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.reparation</code> table reference
     */
    public Reparation(String alias) {
        this(DSL.name(alias), REPARATION);
    }

    /**
     * Create an aliased <code>public.reparation</code> table reference
     */
    public Reparation(Name alias) {
        this(alias, REPARATION);
    }

    /**
     * Create a <code>public.reparation</code> table reference
     */
    public Reparation() {
        this(DSL.name("reparation"), null);
    }

    public <O extends Record> Reparation(Table<O> path, ForeignKey<O, ReparationRecord> childPath, InverseForeignKey<O, ReparationRecord> parentPath) {
        super(path, childPath, parentPath, REPARATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReparationPath extends Reparation implements Path<ReparationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReparationPath(Table<O> path, ForeignKey<O, ReparationRecord> childPath, InverseForeignKey<O, ReparationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReparationPath(Name alias, Table<ReparationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReparationPath as(String alias) {
            return new ReparationPath(DSL.name(alias), this);
        }

        @Override
        public ReparationPath as(Name alias) {
            return new ReparationPath(alias, this);
        }

        @Override
        public ReparationPath as(Table<?> alias) {
            return new ReparationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ReparationRecord, Integer> getIdentity() {
        return (Identity<ReparationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReparationRecord> getPrimaryKey() {
        return Keys.REPARATION_PKEY;
    }

    @Override
    public List<ForeignKey<ReparationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPARATION__REPARATION_ID_ENGINEER_FKEY, Keys.REPARATION__REPARATION_ID_MODEL_FKEY);
    }

    private transient EngineerPath _engineer;

    /**
     * Get the implicit join path to the <code>public.engineer</code> table.
     */
    public EngineerPath engineer() {
        if (_engineer == null)
            _engineer = new EngineerPath(this, Keys.REPARATION__REPARATION_ID_ENGINEER_FKEY, null);

        return _engineer;
    }

    private transient ModelPath _model;

    /**
     * Get the implicit join path to the <code>public.model</code> table.
     */
    public ModelPath model() {
        if (_model == null)
            _model = new ModelPath(this, Keys.REPARATION__REPARATION_ID_MODEL_FKEY, null);

        return _model;
    }

    private transient ReparationDetailPath _reparationDetail;

    /**
     * Get the implicit to-many join path to the
     * <code>public.reparation_detail</code> table
     */
    public ReparationDetailPath reparationDetail() {
        if (_reparationDetail == null)
            _reparationDetail = new ReparationDetailPath(this, null, Keys.REPARATION_DETAIL__REPARATION_DETAIL_ID_REPARATION_FKEY.getInverseKey());

        return _reparationDetail;
    }

    private transient ReparationFeedbackPath _reparationFeedback;

    /**
     * Get the implicit to-many join path to the
     * <code>public.reparation_feedback</code> table
     */
    public ReparationFeedbackPath reparationFeedback() {
        if (_reparationFeedback == null)
            _reparationFeedback = new ReparationFeedbackPath(this, null, Keys.REPARATION_FEEDBACK__REPARATION_FEEDBACK_ID_REPARATION_FKEY.getInverseKey());

        return _reparationFeedback;
    }

    @Override
    public Reparation as(String alias) {
        return new Reparation(DSL.name(alias), this);
    }

    @Override
    public Reparation as(Name alias) {
        return new Reparation(alias, this);
    }

    @Override
    public Reparation as(Table<?> alias) {
        return new Reparation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Reparation rename(String name) {
        return new Reparation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reparation rename(Name name) {
        return new Reparation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reparation rename(Table<?> name) {
        return new Reparation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reparation where(Condition condition) {
        return new Reparation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reparation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reparation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reparation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reparation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reparation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reparation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reparation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reparation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reparation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
