/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.EntryComponent.EntryComponentPath;
import model.tables.records.SupplierRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Supplier extends TableImpl<SupplierRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.supplier</code>
     */
    public static final Supplier SUPPLIER = new Supplier();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupplierRecord> getRecordType() {
        return SupplierRecord.class;
    }

    /**
     * The column <code>public.supplier.id</code>.
     */
    public final TableField<SupplierRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.supplier.name</code>.
     */
    public final TableField<SupplierRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.supplier.telephone</code>.
     */
    public final TableField<SupplierRecord, String> TELEPHONE = createField(DSL.name("telephone"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.supplier.email</code>.
     */
    public final TableField<SupplierRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.supplier.address</code>.
     */
    public final TableField<SupplierRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "");

    private Supplier(Name alias, Table<SupplierRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Supplier(Name alias, Table<SupplierRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.supplier</code> table reference
     */
    public Supplier(String alias) {
        this(DSL.name(alias), SUPPLIER);
    }

    /**
     * Create an aliased <code>public.supplier</code> table reference
     */
    public Supplier(Name alias) {
        this(alias, SUPPLIER);
    }

    /**
     * Create a <code>public.supplier</code> table reference
     */
    public Supplier() {
        this(DSL.name("supplier"), null);
    }

    public <O extends Record> Supplier(Table<O> path, ForeignKey<O, SupplierRecord> childPath, InverseForeignKey<O, SupplierRecord> parentPath) {
        super(path, childPath, parentPath, SUPPLIER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SupplierPath extends Supplier implements Path<SupplierRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SupplierPath(Table<O> path, ForeignKey<O, SupplierRecord> childPath, InverseForeignKey<O, SupplierRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SupplierPath(Name alias, Table<SupplierRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SupplierPath as(String alias) {
            return new SupplierPath(DSL.name(alias), this);
        }

        @Override
        public SupplierPath as(Name alias) {
            return new SupplierPath(alias, this);
        }

        @Override
        public SupplierPath as(Table<?> alias) {
            return new SupplierPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SupplierRecord, Integer> getIdentity() {
        return (Identity<SupplierRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SupplierRecord> getPrimaryKey() {
        return Keys.SUPPLIER_PKEY;
    }

    @Override
    public List<UniqueKey<SupplierRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SUPPLIER_NAME_KEY);
    }

    private transient EntryComponentPath _entryComponent;

    /**
     * Get the implicit to-many join path to the
     * <code>public.entry_component</code> table
     */
    public EntryComponentPath entryComponent() {
        if (_entryComponent == null)
            _entryComponent = new EntryComponentPath(this, null, Keys.ENTRY_COMPONENT__ENTRY_COMPONENT_ID_SUPPLIER_FKEY.getInverseKey());

        return _entryComponent;
    }

    @Override
    public List<Check<SupplierRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("supplier_email_check"), "(((email)::text ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'::text))", true),
            Internal.createCheck(this, DSL.name("supplier_name_check"), "(((name)::text <> ''::text))", true),
            Internal.createCheck(this, DSL.name("supplier_telephone_check"), "(((telephone)::text ~ '^\\+?[0-9]{10,}$'::text))", true)
        );
    }

    @Override
    public Supplier as(String alias) {
        return new Supplier(DSL.name(alias), this);
    }

    @Override
    public Supplier as(Name alias) {
        return new Supplier(alias, this);
    }

    @Override
    public Supplier as(Table<?> alias) {
        return new Supplier(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Supplier rename(String name) {
        return new Supplier(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Supplier rename(Name name) {
        return new Supplier(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Supplier rename(Table<?> name) {
        return new Supplier(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier where(Condition condition) {
        return new Supplier(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Supplier where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Supplier where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Supplier where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Supplier where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
