/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.MvtTicketState.MvtTicketStatePath;
import model.tables.Ticket.TicketPath;
import model.tables.records.TicketStateRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TicketState extends TableImpl<TicketStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ticket_state</code>
     */
    public static final TicketState TICKET_STATE = new TicketState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketStateRecord> getRecordType() {
        return TicketStateRecord.class;
    }

    /**
     * The column <code>public.ticket_state.id</code>.
     */
    public final TableField<TicketStateRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ticket_state.label</code>.
     */
    public final TableField<TicketStateRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private TicketState(Name alias, Table<TicketStateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TicketState(Name alias, Table<TicketStateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ticket_state</code> table reference
     */
    public TicketState(String alias) {
        this(DSL.name(alias), TICKET_STATE);
    }

    /**
     * Create an aliased <code>public.ticket_state</code> table reference
     */
    public TicketState(Name alias) {
        this(alias, TICKET_STATE);
    }

    /**
     * Create a <code>public.ticket_state</code> table reference
     */
    public TicketState() {
        this(DSL.name("ticket_state"), null);
    }

    public <O extends Record> TicketState(Table<O> path, ForeignKey<O, TicketStateRecord> childPath, InverseForeignKey<O, TicketStateRecord> parentPath) {
        super(path, childPath, parentPath, TICKET_STATE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TicketStatePath extends TicketState implements Path<TicketStateRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TicketStatePath(Table<O> path, ForeignKey<O, TicketStateRecord> childPath, InverseForeignKey<O, TicketStateRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TicketStatePath(Name alias, Table<TicketStateRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TicketStatePath as(String alias) {
            return new TicketStatePath(DSL.name(alias), this);
        }

        @Override
        public TicketStatePath as(Name alias) {
            return new TicketStatePath(alias, this);
        }

        @Override
        public TicketStatePath as(Table<?> alias) {
            return new TicketStatePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TicketStateRecord, Integer> getIdentity() {
        return (Identity<TicketStateRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TicketStateRecord> getPrimaryKey() {
        return Keys.TICKET_STATE_PKEY;
    }

    @Override
    public List<UniqueKey<TicketStateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TICKET_STATE_LABEL_KEY);
    }

    private transient MvtTicketStatePath _mvtTicketState;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mvt_ticket_state</code> table
     */
    public MvtTicketStatePath mvtTicketState() {
        if (_mvtTicketState == null)
            _mvtTicketState = new MvtTicketStatePath(this, null, Keys.MVT_TICKET_STATE__MVT_TICKET_STATE_ID_TICKET_STATE_FKEY.getInverseKey());

        return _mvtTicketState;
    }

    private transient TicketPath _ticket;

    /**
     * Get the implicit to-many join path to the <code>public.ticket</code>
     * table
     */
    public TicketPath ticket() {
        if (_ticket == null)
            _ticket = new TicketPath(this, null, Keys.TICKET__TICKET_ID_TICKET_STATE_FKEY.getInverseKey());

        return _ticket;
    }

    @Override
    public List<Check<TicketStateRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ticket_state_label_check"), "(((label)::text <> ''::text))", true)
        );
    }

    @Override
    public TicketState as(String alias) {
        return new TicketState(DSL.name(alias), this);
    }

    @Override
    public TicketState as(Name alias) {
        return new TicketState(alias, this);
    }

    @Override
    public TicketState as(Table<?> alias) {
        return new TicketState(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketState rename(String name) {
        return new TicketState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketState rename(Name name) {
        return new TicketState(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketState rename(Table<?> name) {
        return new TicketState(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketState where(Condition condition) {
        return new TicketState(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketState where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketState where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketState where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketState where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketState where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketState where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketState where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketState whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketState whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
