/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Component.ComponentPath;
import model.tables.Ticket.TicketPath;
import model.tables.records.TicketComponentRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TicketComponent extends TableImpl<TicketComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ticket_component</code>
     */
    public static final TicketComponent TICKET_COMPONENT = new TicketComponent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketComponentRecord> getRecordType() {
        return TicketComponentRecord.class;
    }

    /**
     * The column <code>public.ticket_component.id</code>.
     */
    public final TableField<TicketComponentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ticket_component.id_ticket</code>.
     */
    public final TableField<TicketComponentRecord, Integer> ID_TICKET = createField(DSL.name("id_ticket"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ticket_component.id_component</code>.
     */
    public final TableField<TicketComponentRecord, Integer> ID_COMPONENT = createField(DSL.name("id_component"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ticket_component.quantity</code>.
     */
    public final TableField<TicketComponentRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(13, 2).nullable(false), this, "");

    /**
     * The column <code>public.ticket_component.cost_total</code>.
     */
    public final TableField<TicketComponentRecord, BigDecimal> COST_TOTAL = createField(DSL.name("cost_total"), SQLDataType.NUMERIC(13, 2).nullable(false), this, "");

    private TicketComponent(Name alias, Table<TicketComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TicketComponent(Name alias, Table<TicketComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ticket_component</code> table reference
     */
    public TicketComponent(String alias) {
        this(DSL.name(alias), TICKET_COMPONENT);
    }

    /**
     * Create an aliased <code>public.ticket_component</code> table reference
     */
    public TicketComponent(Name alias) {
        this(alias, TICKET_COMPONENT);
    }

    /**
     * Create a <code>public.ticket_component</code> table reference
     */
    public TicketComponent() {
        this(DSL.name("ticket_component"), null);
    }

    public <O extends Record> TicketComponent(Table<O> path, ForeignKey<O, TicketComponentRecord> childPath, InverseForeignKey<O, TicketComponentRecord> parentPath) {
        super(path, childPath, parentPath, TICKET_COMPONENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TicketComponentPath extends TicketComponent implements Path<TicketComponentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TicketComponentPath(Table<O> path, ForeignKey<O, TicketComponentRecord> childPath, InverseForeignKey<O, TicketComponentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TicketComponentPath(Name alias, Table<TicketComponentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TicketComponentPath as(String alias) {
            return new TicketComponentPath(DSL.name(alias), this);
        }

        @Override
        public TicketComponentPath as(Name alias) {
            return new TicketComponentPath(alias, this);
        }

        @Override
        public TicketComponentPath as(Table<?> alias) {
            return new TicketComponentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TicketComponentRecord, Integer> getIdentity() {
        return (Identity<TicketComponentRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TicketComponentRecord> getPrimaryKey() {
        return Keys.TICKET_COMPONENT_PKEY;
    }

    @Override
    public List<UniqueKey<TicketComponentRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TICKET_COMPONENT_ID_TICKET_ID_COMPONENT_KEY);
    }

    @Override
    public List<ForeignKey<TicketComponentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TICKET_COMPONENT__TICKET_COMPONENT_ID_COMPONENT_FKEY, Keys.TICKET_COMPONENT__TICKET_COMPONENT_ID_TICKET_FKEY);
    }

    private transient ComponentPath _component;

    /**
     * Get the implicit join path to the <code>public.component</code> table.
     */
    public ComponentPath component() {
        if (_component == null)
            _component = new ComponentPath(this, Keys.TICKET_COMPONENT__TICKET_COMPONENT_ID_COMPONENT_FKEY, null);

        return _component;
    }

    private transient TicketPath _ticket;

    /**
     * Get the implicit join path to the <code>public.ticket</code> table.
     */
    public TicketPath ticket() {
        if (_ticket == null)
            _ticket = new TicketPath(this, Keys.TICKET_COMPONENT__TICKET_COMPONENT_ID_TICKET_FKEY, null);

        return _ticket;
    }

    @Override
    public List<Check<TicketComponentRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ticket_component_quantity_check"), "((quantity > (0)::numeric))", true)
        );
    }

    @Override
    public TicketComponent as(String alias) {
        return new TicketComponent(DSL.name(alias), this);
    }

    @Override
    public TicketComponent as(Name alias) {
        return new TicketComponent(alias, this);
    }

    @Override
    public TicketComponent as(Table<?> alias) {
        return new TicketComponent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketComponent rename(String name) {
        return new TicketComponent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketComponent rename(Name name) {
        return new TicketComponent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketComponent rename(Table<?> name) {
        return new TicketComponent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketComponent where(Condition condition) {
        return new TicketComponent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketComponent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketComponent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketComponent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketComponent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketComponent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketComponent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketComponent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketComponent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketComponent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
