/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Component.ComponentPath;
import model.tables.Customer.CustomerPath;
import model.tables.Model.ModelPath;
import model.tables.MvtTicketState.MvtTicketStatePath;
import model.tables.TicketComponent.TicketComponentPath;
import model.tables.TicketState.TicketStatePath;
import model.tables.records.TicketRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ticket extends TableImpl<TicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ticket</code>
     */
    public static final Ticket TICKET = new Ticket();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketRecord> getRecordType() {
        return TicketRecord.class;
    }

    /**
     * The column <code>public.ticket.id</code>.
     */
    public final TableField<TicketRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ticket.price_reparation</code>.
     */
    public final TableField<TicketRecord, BigDecimal> PRICE_REPARATION = createField(DSL.name("price_reparation"), SQLDataType.NUMERIC(13, 2).nullable(false), this, "");

    /**
     * The column <code>public.ticket.id_customer</code>.
     */
    public final TableField<TicketRecord, Integer> ID_CUSTOMER = createField(DSL.name("id_customer"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ticket.id_model</code>.
     */
    public final TableField<TicketRecord, Integer> ID_MODEL = createField(DSL.name("id_model"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ticket.diagnostic</code>.
     */
    public final TableField<TicketRecord, String> DIAGNOSTIC = createField(DSL.name("diagnostic"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.ticket.id_ticket_state</code>.
     */
    public final TableField<TicketRecord, Integer> ID_TICKET_STATE = createField(DSL.name("id_ticket_state"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.ticket.date_start</code>.
     */
    public final TableField<TicketRecord, LocalDateTime> DATE_START = createField(DSL.name("date_start"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.ticket.date_end</code>.
     */
    public final TableField<TicketRecord, LocalDateTime> DATE_END = createField(DSL.name("date_end"), SQLDataType.LOCALDATETIME(6), this, "");

    private Ticket(Name alias, Table<TicketRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Ticket(Name alias, Table<TicketRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ticket</code> table reference
     */
    public Ticket(String alias) {
        this(DSL.name(alias), TICKET);
    }

    /**
     * Create an aliased <code>public.ticket</code> table reference
     */
    public Ticket(Name alias) {
        this(alias, TICKET);
    }

    /**
     * Create a <code>public.ticket</code> table reference
     */
    public Ticket() {
        this(DSL.name("ticket"), null);
    }

    public <O extends Record> Ticket(Table<O> path, ForeignKey<O, TicketRecord> childPath, InverseForeignKey<O, TicketRecord> parentPath) {
        super(path, childPath, parentPath, TICKET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TicketPath extends Ticket implements Path<TicketRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TicketPath(Table<O> path, ForeignKey<O, TicketRecord> childPath, InverseForeignKey<O, TicketRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TicketPath(Name alias, Table<TicketRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TicketPath as(String alias) {
            return new TicketPath(DSL.name(alias), this);
        }

        @Override
        public TicketPath as(Name alias) {
            return new TicketPath(alias, this);
        }

        @Override
        public TicketPath as(Table<?> alias) {
            return new TicketPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TicketRecord, Integer> getIdentity() {
        return (Identity<TicketRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TicketRecord> getPrimaryKey() {
        return Keys.TICKET_PKEY;
    }

    @Override
    public List<ForeignKey<TicketRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TICKET__TICKET_ID_CUSTOMER_FKEY, Keys.TICKET__TICKET_ID_MODEL_FKEY, Keys.TICKET__TICKET_ID_TICKET_STATE_FKEY);
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit join path to the <code>public.customer</code> table.
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, Keys.TICKET__TICKET_ID_CUSTOMER_FKEY, null);

        return _customer;
    }

    private transient ModelPath _model;

    /**
     * Get the implicit join path to the <code>public.model</code> table.
     */
    public ModelPath model() {
        if (_model == null)
            _model = new ModelPath(this, Keys.TICKET__TICKET_ID_MODEL_FKEY, null);

        return _model;
    }

    private transient TicketStatePath _ticketState;

    /**
     * Get the implicit join path to the <code>public.ticket_state</code> table.
     */
    public TicketStatePath ticketState() {
        if (_ticketState == null)
            _ticketState = new TicketStatePath(this, Keys.TICKET__TICKET_ID_TICKET_STATE_FKEY, null);

        return _ticketState;
    }

    private transient MvtTicketStatePath _mvtTicketState;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mvt_ticket_state</code> table
     */
    public MvtTicketStatePath mvtTicketState() {
        if (_mvtTicketState == null)
            _mvtTicketState = new MvtTicketStatePath(this, null, Keys.MVT_TICKET_STATE__MVT_TICKET_STATE_ID_TICKET_FKEY.getInverseKey());

        return _mvtTicketState;
    }

    private transient TicketComponentPath _ticketComponent;

    /**
     * Get the implicit to-many join path to the
     * <code>public.ticket_component</code> table
     */
    public TicketComponentPath ticketComponent() {
        if (_ticketComponent == null)
            _ticketComponent = new TicketComponentPath(this, null, Keys.TICKET_COMPONENT__TICKET_COMPONENT_ID_TICKET_FKEY.getInverseKey());

        return _ticketComponent;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.component</code> table
     */
    public ComponentPath component() {
        return ticketComponent().component();
    }

    @Override
    public List<Check<TicketRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ticket_check"), "(((id_ticket_state IS NULL) OR (id_ticket_state = 1) OR (id_ticket_state = 2) OR (diagnostic IS NOT NULL)))", true),
            Internal.createCheck(this, DSL.name("ticket_price_reparation_check"), "((price_reparation >= (0)::numeric))", true)
        );
    }

    @Override
    public Ticket as(String alias) {
        return new Ticket(DSL.name(alias), this);
    }

    @Override
    public Ticket as(Name alias) {
        return new Ticket(alias, this);
    }

    @Override
    public Ticket as(Table<?> alias) {
        return new Ticket(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ticket rename(String name) {
        return new Ticket(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ticket rename(Name name) {
        return new Ticket(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ticket rename(Table<?> name) {
        return new Ticket(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket where(Condition condition) {
        return new Ticket(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ticket where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ticket where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ticket where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ticket where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
