/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.EntryComponent.EntryComponentPath;
import model.tables.Ticket.TicketPath;
import model.tables.records.TicketStockWithdrawRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TicketStockWithdraw extends TableImpl<TicketStockWithdrawRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ticket_stock_withdraw</code>
     */
    public static final TicketStockWithdraw TICKET_STOCK_WITHDRAW = new TicketStockWithdraw();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketStockWithdrawRecord> getRecordType() {
        return TicketStockWithdrawRecord.class;
    }

    /**
     * The column <code>public.ticket_stock_withdraw.id</code>.
     */
    public final TableField<TicketStockWithdrawRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ticket_stock_withdraw.id_ticket</code>.
     */
    public final TableField<TicketStockWithdrawRecord, Integer> ID_TICKET = createField(DSL.name("id_ticket"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ticket_stock_withdraw.id_entry_component</code>.
     */
    public final TableField<TicketStockWithdrawRecord, Integer> ID_ENTRY_COMPONENT = createField(DSL.name("id_entry_component"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ticket_stock_withdraw.quantity</code>.
     */
    public final TableField<TicketStockWithdrawRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(13, 2).nullable(false), this, "");

    private TicketStockWithdraw(Name alias, Table<TicketStockWithdrawRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TicketStockWithdraw(Name alias, Table<TicketStockWithdrawRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ticket_stock_withdraw</code> table
     * reference
     */
    public TicketStockWithdraw(String alias) {
        this(DSL.name(alias), TICKET_STOCK_WITHDRAW);
    }

    /**
     * Create an aliased <code>public.ticket_stock_withdraw</code> table
     * reference
     */
    public TicketStockWithdraw(Name alias) {
        this(alias, TICKET_STOCK_WITHDRAW);
    }

    /**
     * Create a <code>public.ticket_stock_withdraw</code> table reference
     */
    public TicketStockWithdraw() {
        this(DSL.name("ticket_stock_withdraw"), null);
    }

    public <O extends Record> TicketStockWithdraw(Table<O> path, ForeignKey<O, TicketStockWithdrawRecord> childPath, InverseForeignKey<O, TicketStockWithdrawRecord> parentPath) {
        super(path, childPath, parentPath, TICKET_STOCK_WITHDRAW);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TicketStockWithdrawPath extends TicketStockWithdraw implements Path<TicketStockWithdrawRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TicketStockWithdrawPath(Table<O> path, ForeignKey<O, TicketStockWithdrawRecord> childPath, InverseForeignKey<O, TicketStockWithdrawRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TicketStockWithdrawPath(Name alias, Table<TicketStockWithdrawRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TicketStockWithdrawPath as(String alias) {
            return new TicketStockWithdrawPath(DSL.name(alias), this);
        }

        @Override
        public TicketStockWithdrawPath as(Name alias) {
            return new TicketStockWithdrawPath(alias, this);
        }

        @Override
        public TicketStockWithdrawPath as(Table<?> alias) {
            return new TicketStockWithdrawPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TicketStockWithdrawRecord, Integer> getIdentity() {
        return (Identity<TicketStockWithdrawRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TicketStockWithdrawRecord> getPrimaryKey() {
        return Keys.TICKET_STOCK_WITHDRAW_PKEY;
    }

    @Override
    public List<UniqueKey<TicketStockWithdrawRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TICKET_STOCK_WITHDRAW_ID_TICKET_ID_ENTRY_COMPONENT_KEY);
    }

    @Override
    public List<ForeignKey<TicketStockWithdrawRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TICKET_STOCK_WITHDRAW__TICKET_STOCK_WITHDRAW_ID_ENTRY_COMPONENT_FKEY, Keys.TICKET_STOCK_WITHDRAW__TICKET_STOCK_WITHDRAW_ID_TICKET_FKEY);
    }

    private transient EntryComponentPath _entryComponent;

    /**
     * Get the implicit join path to the <code>public.entry_component</code>
     * table.
     */
    public EntryComponentPath entryComponent() {
        if (_entryComponent == null)
            _entryComponent = new EntryComponentPath(this, Keys.TICKET_STOCK_WITHDRAW__TICKET_STOCK_WITHDRAW_ID_ENTRY_COMPONENT_FKEY, null);

        return _entryComponent;
    }

    private transient TicketPath _ticket;

    /**
     * Get the implicit join path to the <code>public.ticket</code> table.
     */
    public TicketPath ticket() {
        if (_ticket == null)
            _ticket = new TicketPath(this, Keys.TICKET_STOCK_WITHDRAW__TICKET_STOCK_WITHDRAW_ID_TICKET_FKEY, null);

        return _ticket;
    }

    @Override
    public List<Check<TicketStockWithdrawRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ticket_stock_withdraw_quantity_check"), "((quantity > (0)::numeric))", true)
        );
    }

    @Override
    public TicketStockWithdraw as(String alias) {
        return new TicketStockWithdraw(DSL.name(alias), this);
    }

    @Override
    public TicketStockWithdraw as(Name alias) {
        return new TicketStockWithdraw(alias, this);
    }

    @Override
    public TicketStockWithdraw as(Table<?> alias) {
        return new TicketStockWithdraw(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketStockWithdraw rename(String name) {
        return new TicketStockWithdraw(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketStockWithdraw rename(Name name) {
        return new TicketStockWithdraw(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TicketStockWithdraw rename(Table<?> name) {
        return new TicketStockWithdraw(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketStockWithdraw where(Condition condition) {
        return new TicketStockWithdraw(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketStockWithdraw where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketStockWithdraw where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketStockWithdraw where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketStockWithdraw where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketStockWithdraw where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketStockWithdraw where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TicketStockWithdraw where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketStockWithdraw whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TicketStockWithdraw whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
