/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import model.Public;
import model.tables.records.VEngineerCommissionRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VEngineerCommission extends TableImpl<VEngineerCommissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_engineer_commission</code>
     */
    public static final VEngineerCommission V_ENGINEER_COMMISSION = new VEngineerCommission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VEngineerCommissionRecord> getRecordType() {
        return VEngineerCommissionRecord.class;
    }

    /**
     * The column <code>public.v_engineer_commission.id</code>.
     */
    public final TableField<VEngineerCommissionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_engineer_commission.name</code>.
     */
    public final TableField<VEngineerCommissionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_engineer_commission.telephone</code>.
     */
    public final TableField<VEngineerCommissionRecord, String> TELEPHONE = createField(DSL.name("telephone"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.v_engineer_commission.email</code>.
     */
    public final TableField<VEngineerCommissionRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_engineer_commission.address</code>.
     */
    public final TableField<VEngineerCommissionRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_engineer_commission.id_gender</code>.
     */
    public final TableField<VEngineerCommissionRecord, Integer> ID_GENDER = createField(DSL.name("id_gender"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_engineer_commission.date_end</code>.
     */
    public final TableField<VEngineerCommissionRecord, LocalDateTime> DATE_END = createField(DSL.name("date_end"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_engineer_commission.gender</code>.
     */
    public final TableField<VEngineerCommissionRecord, String> GENDER = createField(DSL.name("gender"), SQLDataType.VARCHAR(55), this, "");

    /**
     * The column <code>public.v_engineer_commission.commission</code>.
     */
    public final TableField<VEngineerCommissionRecord, BigDecimal> COMMISSION = createField(DSL.name("commission"), SQLDataType.NUMERIC, this, "");

    private VEngineerCommission(Name alias, Table<VEngineerCommissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VEngineerCommission(Name alias, Table<VEngineerCommissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_engineer_commission" as  SELECT eng.id,
         eng.name,
         eng.telephone,
         eng.email,
         eng.address,
         eng.id_gender,
         tic.date_end,
         gd.gender,
             CASE
                 WHEN (tic.price_reparation >= (200000)::numeric) THEN ((tic.price_reparation * (5)::numeric) / (100)::numeric)
                 ELSE (0)::numeric
             END AS commission
        FROM ((engineer eng
          JOIN ticket tic ON ((tic.id_engineer = eng.id)))
          JOIN gender gd ON ((gd.id = eng.id_gender)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_engineer_commission</code> table
     * reference
     */
    public VEngineerCommission(String alias) {
        this(DSL.name(alias), V_ENGINEER_COMMISSION);
    }

    /**
     * Create an aliased <code>public.v_engineer_commission</code> table
     * reference
     */
    public VEngineerCommission(Name alias) {
        this(alias, V_ENGINEER_COMMISSION);
    }

    /**
     * Create a <code>public.v_engineer_commission</code> table reference
     */
    public VEngineerCommission() {
        this(DSL.name("v_engineer_commission"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VEngineerCommission as(String alias) {
        return new VEngineerCommission(DSL.name(alias), this);
    }

    @Override
    public VEngineerCommission as(Name alias) {
        return new VEngineerCommission(alias, this);
    }

    @Override
    public VEngineerCommission as(Table<?> alias) {
        return new VEngineerCommission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VEngineerCommission rename(String name) {
        return new VEngineerCommission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VEngineerCommission rename(Name name) {
        return new VEngineerCommission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VEngineerCommission rename(Table<?> name) {
        return new VEngineerCommission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VEngineerCommission where(Condition condition) {
        return new VEngineerCommission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VEngineerCommission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VEngineerCommission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VEngineerCommission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VEngineerCommission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VEngineerCommission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VEngineerCommission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VEngineerCommission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VEngineerCommission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VEngineerCommission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
