/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import model.Public;
import model.tables.records.VLabelTicketRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelTicket extends TableImpl<VLabelTicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_label_ticket</code>
     */
    public static final VLabelTicket V_LABEL_TICKET = new VLabelTicket();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelTicketRecord> getRecordType() {
        return VLabelTicketRecord.class;
    }

    /**
     * The column <code>public.v_label_ticket.id</code>.
     */
    public final TableField<VLabelTicketRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket.price_reparation</code>.
     */
    public final TableField<VLabelTicketRecord, BigDecimal> PRICE_REPARATION = createField(DSL.name("price_reparation"), SQLDataType.NUMERIC(13, 2), this, "");

    /**
     * The column <code>public.v_label_ticket.id_customer</code>.
     */
    public final TableField<VLabelTicketRecord, Integer> ID_CUSTOMER = createField(DSL.name("id_customer"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket.name</code>.
     */
    public final TableField<VLabelTicketRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_ticket.telephone</code>.
     */
    public final TableField<VLabelTicketRecord, String> TELEPHONE = createField(DSL.name("telephone"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.v_label_ticket.email</code>.
     */
    public final TableField<VLabelTicketRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_ticket.address</code>.
     */
    public final TableField<VLabelTicketRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_ticket.id_model</code>.
     */
    public final TableField<VLabelTicketRecord, Integer> ID_MODEL = createField(DSL.name("id_model"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket.serial_number</code>.
     */
    public final TableField<VLabelTicketRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_label_ticket.id_model_category</code>.
     */
    public final TableField<VLabelTicketRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket.model_category</code>.
     */
    public final TableField<VLabelTicketRecord, String> MODEL_CATEGORY = createField(DSL.name("model_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_ticket.id_brand</code>.
     */
    public final TableField<VLabelTicketRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket.brand</code>.
     */
    public final TableField<VLabelTicketRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_ticket.description</code>.
     */
    public final TableField<VLabelTicketRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_label_ticket.diagnostic</code>.
     */
    public final TableField<VLabelTicketRecord, String> DIAGNOSTIC = createField(DSL.name("diagnostic"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_label_ticket.id_ticket_state</code>.
     */
    public final TableField<VLabelTicketRecord, Integer> ID_TICKET_STATE = createField(DSL.name("id_ticket_state"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket.ticket_state</code>.
     */
    public final TableField<VLabelTicketRecord, String> TICKET_STATE = createField(DSL.name("ticket_state"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_ticket.date_start</code>.
     */
    public final TableField<VLabelTicketRecord, LocalDateTime> DATE_START = createField(DSL.name("date_start"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_label_ticket.date_end</code>.
     */
    public final TableField<VLabelTicketRecord, LocalDateTime> DATE_END = createField(DSL.name("date_end"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_label_ticket.engineer</code>.
     */
    public final TableField<VLabelTicketRecord, String> ENGINEER = createField(DSL.name("engineer"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_ticket.id_engineer</code>.
     */
    public final TableField<VLabelTicketRecord, Integer> ID_ENGINEER = createField(DSL.name("id_engineer"), SQLDataType.INTEGER, this, "");

    private VLabelTicket(Name alias, Table<VLabelTicketRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelTicket(Name alias, Table<VLabelTicketRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_ticket" as  SELECT t.id,
         t.price_reparation,
         t.id_customer,
         c.name,
         c.telephone,
         c.email,
         c.address,
         t.id_model,
         m.serial_number,
         m.id_model_category,
         mc.label AS model_category,
         m.id_brand,
         b.label AS brand,
         m.description,
         t.diagnostic,
         t.id_ticket_state,
         ts.label AS ticket_state,
         t.date_start,
         t.date_end,
         e.name AS engineer,
         e.id AS id_engineer
        FROM ((((((ticket t
          JOIN customer c ON ((t.id_customer = c.id)))
          JOIN engineer e ON ((t.id_engineer = e.id)))
          JOIN model m ON ((t.id_model = m.id)))
          JOIN model_category mc ON ((m.id_model_category = mc.id)))
          JOIN brand b ON ((m.id_brand = b.id)))
          JOIN ticket_state ts ON ((t.id_ticket_state = ts.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_ticket</code> table reference
     */
    public VLabelTicket(String alias) {
        this(DSL.name(alias), V_LABEL_TICKET);
    }

    /**
     * Create an aliased <code>public.v_label_ticket</code> table reference
     */
    public VLabelTicket(Name alias) {
        this(alias, V_LABEL_TICKET);
    }

    /**
     * Create a <code>public.v_label_ticket</code> table reference
     */
    public VLabelTicket() {
        this(DSL.name("v_label_ticket"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelTicket as(String alias) {
        return new VLabelTicket(DSL.name(alias), this);
    }

    @Override
    public VLabelTicket as(Name alias) {
        return new VLabelTicket(alias, this);
    }

    @Override
    public VLabelTicket as(Table<?> alias) {
        return new VLabelTicket(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelTicket rename(String name) {
        return new VLabelTicket(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelTicket rename(Name name) {
        return new VLabelTicket(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelTicket rename(Table<?> name) {
        return new VLabelTicket(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicket where(Condition condition) {
        return new VLabelTicket(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicket where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicket where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicket where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelTicket where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelTicket where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelTicket where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelTicket where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicket whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicket whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
