/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Collection;

import model.Public;
import model.tables.records.VLabelModelRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelModel extends TableImpl<VLabelModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_label_model</code>
     */
    public static final VLabelModel V_LABEL_MODEL = new VLabelModel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelModelRecord> getRecordType() {
        return VLabelModelRecord.class;
    }

    /**
     * The column <code>public.v_label_model.id</code>.
     */
    public final TableField<VLabelModelRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_model.serial_number</code>.
     */
    public final TableField<VLabelModelRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_label_model.id_model_category</code>.
     */
    public final TableField<VLabelModelRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_model.model_category</code>.
     */
    public final TableField<VLabelModelRecord, String> MODEL_CATEGORY = createField(DSL.name("model_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_model.id_brand</code>.
     */
    public final TableField<VLabelModelRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_model.brand</code>.
     */
    public final TableField<VLabelModelRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_model.description</code>.
     */
    public final TableField<VLabelModelRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private VLabelModel(Name alias, Table<VLabelModelRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelModel(Name alias, Table<VLabelModelRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_model" as  SELECT m.id,
         m.serial_number,
         m.id_model_category,
         mc.label AS model_category,
         m.id_brand,
         b.label AS brand,
         m.description
        FROM ((model m
          JOIN model_category mc ON ((m.id_model_category = mc.id)))
          JOIN brand b ON ((m.id_brand = b.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_model</code> table reference
     */
    public VLabelModel(String alias) {
        this(DSL.name(alias), V_LABEL_MODEL);
    }

    /**
     * Create an aliased <code>public.v_label_model</code> table reference
     */
    public VLabelModel(Name alias) {
        this(alias, V_LABEL_MODEL);
    }

    /**
     * Create a <code>public.v_label_model</code> table reference
     */
    public VLabelModel() {
        this(DSL.name("v_label_model"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelModel as(String alias) {
        return new VLabelModel(DSL.name(alias), this);
    }

    @Override
    public VLabelModel as(Name alias) {
        return new VLabelModel(alias, this);
    }

    @Override
    public VLabelModel as(Table<?> alias) {
        return new VLabelModel(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelModel rename(String name) {
        return new VLabelModel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelModel rename(Name name) {
        return new VLabelModel(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelModel rename(Table<?> name) {
        return new VLabelModel(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelModel where(Condition condition) {
        return new VLabelModel(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelModel where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelModel where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelModel where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelModel where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelModel where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelModel where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelModel where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelModel whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelModel whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
