/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import model.Public;
import model.tables.records.VLabelMvtTicketStateRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelMvtTicketState extends TableImpl<VLabelMvtTicketStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_label_mvt_ticket_state</code>
     */
    public static final VLabelMvtTicketState V_LABEL_MVT_TICKET_STATE = new VLabelMvtTicketState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelMvtTicketStateRecord> getRecordType() {
        return VLabelMvtTicketStateRecord.class;
    }

    /**
     * The column <code>public.v_label_mvt_ticket_state.id</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.datetime</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, LocalDateTime> DATETIME = createField(DSL.name("datetime"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.id_ticket</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, Integer> ID_TICKET = createField(DSL.name("id_ticket"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.price_reparation</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, BigDecimal> PRICE_REPARATION = createField(DSL.name("price_reparation"), SQLDataType.NUMERIC(13, 2), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.id_customer</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, Integer> ID_CUSTOMER = createField(DSL.name("id_customer"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.name</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.telephone</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> TELEPHONE = createField(DSL.name("telephone"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.email</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.address</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.id_model</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, Integer> ID_MODEL = createField(DSL.name("id_model"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.serial_number</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>public.v_label_mvt_ticket_state.id_model_category</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.model_category</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> MODEL_CATEGORY = createField(DSL.name("model_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.id_brand</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.brand</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.description</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.diagnostic</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> DIAGNOSTIC = createField(DSL.name("diagnostic"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.id_ticket_state</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, Integer> ID_TICKET_STATE = createField(DSL.name("id_ticket_state"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.ticket_state</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, String> TICKET_STATE = createField(DSL.name("ticket_state"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.date_start</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, LocalDateTime> DATE_START = createField(DSL.name("date_start"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_label_mvt_ticket_state.date_end</code>.
     */
    public final TableField<VLabelMvtTicketStateRecord, LocalDateTime> DATE_END = createField(DSL.name("date_end"), SQLDataType.LOCALDATETIME(6), this, "");

    private VLabelMvtTicketState(Name alias, Table<VLabelMvtTicketStateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelMvtTicketState(Name alias, Table<VLabelMvtTicketStateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_mvt_ticket_state" as  SELECT mts.id,
         mts.datetime,
         mts.id_ticket,
         t.price_reparation,
         t.id_customer,
         c.name,
         c.telephone,
         c.email,
         c.address,
         t.id_model,
         m.serial_number,
         m.id_model_category,
         mc.label AS model_category,
         m.id_brand,
         b.label AS brand,
         m.description,
         t.diagnostic,
         t.id_ticket_state,
         ts.label AS ticket_state,
         t.date_start,
         t.date_end
        FROM ((((((mvt_ticket_state mts
          JOIN ticket t ON ((mts.id_ticket = t.id)))
          JOIN customer c ON ((t.id_customer = c.id)))
          JOIN model m ON ((t.id_model = m.id)))
          JOIN model_category mc ON ((m.id_model_category = mc.id)))
          JOIN brand b ON ((m.id_brand = b.id)))
          JOIN ticket_state ts ON ((mts.id_ticket_state = ts.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_mvt_ticket_state</code> table
     * reference
     */
    public VLabelMvtTicketState(String alias) {
        this(DSL.name(alias), V_LABEL_MVT_TICKET_STATE);
    }

    /**
     * Create an aliased <code>public.v_label_mvt_ticket_state</code> table
     * reference
     */
    public VLabelMvtTicketState(Name alias) {
        this(alias, V_LABEL_MVT_TICKET_STATE);
    }

    /**
     * Create a <code>public.v_label_mvt_ticket_state</code> table reference
     */
    public VLabelMvtTicketState() {
        this(DSL.name("v_label_mvt_ticket_state"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelMvtTicketState as(String alias) {
        return new VLabelMvtTicketState(DSL.name(alias), this);
    }

    @Override
    public VLabelMvtTicketState as(Name alias) {
        return new VLabelMvtTicketState(alias, this);
    }

    @Override
    public VLabelMvtTicketState as(Table<?> alias) {
        return new VLabelMvtTicketState(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelMvtTicketState rename(String name) {
        return new VLabelMvtTicketState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelMvtTicketState rename(Name name) {
        return new VLabelMvtTicketState(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelMvtTicketState rename(Table<?> name) {
        return new VLabelMvtTicketState(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelMvtTicketState where(Condition condition) {
        return new VLabelMvtTicketState(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelMvtTicketState where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelMvtTicketState where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelMvtTicketState where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelMvtTicketState where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelMvtTicketState where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelMvtTicketState where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelMvtTicketState where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelMvtTicketState whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelMvtTicketState whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
