/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Collection;

import model.Public;
import model.tables.records.VLabelComponentRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelComponent extends TableImpl<VLabelComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_label_component</code>
     */
    public static final VLabelComponent V_LABEL_COMPONENT = new VLabelComponent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelComponentRecord> getRecordType() {
        return VLabelComponentRecord.class;
    }

    /**
     * The column <code>public.v_label_component.id</code>.
     */
    public final TableField<VLabelComponentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_component.serial_number</code>.
     */
    public final TableField<VLabelComponentRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_label_component.id_component_category</code>.
     */
    public final TableField<VLabelComponentRecord, Integer> ID_COMPONENT_CATEGORY = createField(DSL.name("id_component_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_component.component_category</code>.
     */
    public final TableField<VLabelComponentRecord, String> COMPONENT_CATEGORY = createField(DSL.name("component_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_component.id_model_category</code>.
     */
    public final TableField<VLabelComponentRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_component.model_category</code>.
     */
    public final TableField<VLabelComponentRecord, String> MODEL_CATEGORY = createField(DSL.name("model_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_component.id_brand</code>.
     */
    public final TableField<VLabelComponentRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_component.brand</code>.
     */
    public final TableField<VLabelComponentRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_component.description</code>.
     */
    public final TableField<VLabelComponentRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private VLabelComponent(Name alias, Table<VLabelComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelComponent(Name alias, Table<VLabelComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_component" as  SELECT c.id,
         c.serial_number,
         c.id_component_category,
         cc.label AS component_category,
         c.id_model_category,
         mc.label AS model_category,
         c.id_brand,
         b.label AS brand,
         c.description
        FROM (((component c
          JOIN component_category cc ON ((c.id_component_category = cc.id)))
          JOIN model_category mc ON ((c.id_model_category = mc.id)))
          JOIN brand b ON ((c.id_brand = b.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_component</code> table reference
     */
    public VLabelComponent(String alias) {
        this(DSL.name(alias), V_LABEL_COMPONENT);
    }

    /**
     * Create an aliased <code>public.v_label_component</code> table reference
     */
    public VLabelComponent(Name alias) {
        this(alias, V_LABEL_COMPONENT);
    }

    /**
     * Create a <code>public.v_label_component</code> table reference
     */
    public VLabelComponent() {
        this(DSL.name("v_label_component"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelComponent as(String alias) {
        return new VLabelComponent(DSL.name(alias), this);
    }

    @Override
    public VLabelComponent as(Name alias) {
        return new VLabelComponent(alias, this);
    }

    @Override
    public VLabelComponent as(Table<?> alias) {
        return new VLabelComponent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelComponent rename(String name) {
        return new VLabelComponent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelComponent rename(Name name) {
        return new VLabelComponent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelComponent rename(Table<?> name) {
        return new VLabelComponent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelComponent where(Condition condition) {
        return new VLabelComponent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelComponent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelComponent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelComponent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelComponent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelComponent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelComponent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelComponent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelComponent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelComponent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
