/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.time.LocalDate;
import java.util.Collection;

import model.Public;
import model.tables.records.VLabelReparationFeedbackRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelReparationFeedback extends TableImpl<VLabelReparationFeedbackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_label_reparation_feedback</code>
     */
    public static final VLabelReparationFeedback V_LABEL_REPARATION_FEEDBACK = new VLabelReparationFeedback();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelReparationFeedbackRecord> getRecordType() {
        return VLabelReparationFeedbackRecord.class;
    }

    /**
     * The column <code>public.v_label_reparation_feedback.id</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.date</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.id_customer</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, Integer> ID_CUSTOMER = createField(DSL.name("id_customer"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.id_reparation</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, Integer> ID_REPARATION = createField(DSL.name("id_reparation"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.name</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.date_start</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, LocalDate> DATE_START = createField(DSL.name("date_start"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.price</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, Double> PRICE = createField(DSL.name("price"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.id_model</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, Integer> ID_MODEL = createField(DSL.name("id_model"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.serial_number</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>public.v_label_reparation_feedback.id_model_category</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.v_label_reparation_feedback.model_category</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, String> MODEL_CATEGORY = createField(DSL.name("model_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.id_brand</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.brand</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_reparation_feedback.description</code>.
     */
    public final TableField<VLabelReparationFeedbackRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private VLabelReparationFeedback(Name alias, Table<VLabelReparationFeedbackRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelReparationFeedback(Name alias, Table<VLabelReparationFeedbackRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_reparation_feedback" as  SELECT rf.id,
         rf.date,
         rf.id_customer,
         rf.id_reparation,
         c.name,
         vlr.date AS date_start,
         vlr.price,
         vlr.id_model,
         vlr.serial_number,
         vlr.id_model_category,
         vlr.model_category,
         vlr.id_brand,
         vlr.brand,
         vlr.description
        FROM ((reparation_feedback rf
          JOIN customer c ON ((rf.id_customer = c.id)))
          JOIN v_label_reparation vlr ON ((rf.id_reparation = vlr.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_reparation_feedback</code> table
     * reference
     */
    public VLabelReparationFeedback(String alias) {
        this(DSL.name(alias), V_LABEL_REPARATION_FEEDBACK);
    }

    /**
     * Create an aliased <code>public.v_label_reparation_feedback</code> table
     * reference
     */
    public VLabelReparationFeedback(Name alias) {
        this(alias, V_LABEL_REPARATION_FEEDBACK);
    }

    /**
     * Create a <code>public.v_label_reparation_feedback</code> table reference
     */
    public VLabelReparationFeedback() {
        this(DSL.name("v_label_reparation_feedback"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelReparationFeedback as(String alias) {
        return new VLabelReparationFeedback(DSL.name(alias), this);
    }

    @Override
    public VLabelReparationFeedback as(Name alias) {
        return new VLabelReparationFeedback(alias, this);
    }

    @Override
    public VLabelReparationFeedback as(Table<?> alias) {
        return new VLabelReparationFeedback(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelReparationFeedback rename(String name) {
        return new VLabelReparationFeedback(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelReparationFeedback rename(Name name) {
        return new VLabelReparationFeedback(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelReparationFeedback rename(Table<?> name) {
        return new VLabelReparationFeedback(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparationFeedback where(Condition condition) {
        return new VLabelReparationFeedback(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparationFeedback where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparationFeedback where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparationFeedback where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReparationFeedback where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReparationFeedback where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReparationFeedback where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReparationFeedback where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparationFeedback whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparationFeedback whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
