/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.time.LocalDate;
import java.util.Collection;

import model.Public;
import model.tables.records.VLabelReparationRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelReparation extends TableImpl<VLabelReparationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_label_reparation</code>
     */
    public static final VLabelReparation V_LABEL_REPARATION = new VLabelReparation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelReparationRecord> getRecordType() {
        return VLabelReparationRecord.class;
    }

    /**
     * The column <code>public.v_label_reparation.id</code>.
     */
    public final TableField<VLabelReparationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reparation.date</code>.
     */
    public final TableField<VLabelReparationRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.v_label_reparation.price</code>.
     */
    public final TableField<VLabelReparationRecord, Double> PRICE = createField(DSL.name("price"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_label_reparation.id_model</code>.
     */
    public final TableField<VLabelReparationRecord, Integer> ID_MODEL = createField(DSL.name("id_model"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reparation.serial_number</code>.
     */
    public final TableField<VLabelReparationRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_label_reparation.id_model_category</code>.
     */
    public final TableField<VLabelReparationRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reparation.model_category</code>.
     */
    public final TableField<VLabelReparationRecord, String> MODEL_CATEGORY = createField(DSL.name("model_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_reparation.id_brand</code>.
     */
    public final TableField<VLabelReparationRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reparation.brand</code>.
     */
    public final TableField<VLabelReparationRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_reparation.description</code>.
     */
    public final TableField<VLabelReparationRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private VLabelReparation(Name alias, Table<VLabelReparationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelReparation(Name alias, Table<VLabelReparationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_reparation" as  SELECT r.id,
         r.date,
         r.price,
         r.id_model,
         m.serial_number,
         m.id_model_category,
         mc.label AS model_category,
         m.id_brand,
         b.label AS brand,
         m.description
        FROM (((reparation r
          JOIN model m ON ((r.id_model = m.id)))
          JOIN model_category mc ON ((m.id_model_category = mc.id)))
          JOIN brand b ON ((m.id_brand = b.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_reparation</code> table reference
     */
    public VLabelReparation(String alias) {
        this(DSL.name(alias), V_LABEL_REPARATION);
    }

    /**
     * Create an aliased <code>public.v_label_reparation</code> table reference
     */
    public VLabelReparation(Name alias) {
        this(alias, V_LABEL_REPARATION);
    }

    /**
     * Create a <code>public.v_label_reparation</code> table reference
     */
    public VLabelReparation() {
        this(DSL.name("v_label_reparation"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelReparation as(String alias) {
        return new VLabelReparation(DSL.name(alias), this);
    }

    @Override
    public VLabelReparation as(Name alias) {
        return new VLabelReparation(alias, this);
    }

    @Override
    public VLabelReparation as(Table<?> alias) {
        return new VLabelReparation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelReparation rename(String name) {
        return new VLabelReparation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelReparation rename(Name name) {
        return new VLabelReparation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelReparation rename(Table<?> name) {
        return new VLabelReparation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparation where(Condition condition) {
        return new VLabelReparation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReparation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReparation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReparation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReparation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReparation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
