/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import model.Public;
import model.tables.records.VLabelTicketComponentRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelTicketComponent extends TableImpl<VLabelTicketComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_label_ticket_component</code>
     */
    public static final VLabelTicketComponent V_LABEL_TICKET_COMPONENT = new VLabelTicketComponent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelTicketComponentRecord> getRecordType() {
        return VLabelTicketComponentRecord.class;
    }

    /**
     * The column <code>public.v_label_ticket_component.id</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket_component.id_ticket</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_TICKET = createField(DSL.name("id_ticket"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket_component.price_reparation</code>.
     */
    public final TableField<VLabelTicketComponentRecord, BigDecimal> PRICE_REPARATION = createField(DSL.name("price_reparation"), SQLDataType.NUMERIC(13, 2), this, "");

    /**
     * The column <code>public.v_label_ticket_component.id_customer</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_CUSTOMER = createField(DSL.name("id_customer"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket_component.name</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_ticket_component.telephone</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> TELEPHONE = createField(DSL.name("telephone"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.v_label_ticket_component.email</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_ticket_component.address</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_ticket_component.id_model</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_MODEL = createField(DSL.name("id_model"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket_component.serial_number</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>public.v_label_ticket_component.id_model_category</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket_component.model_category</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> MODEL_CATEGORY = createField(DSL.name("model_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_ticket_component.id_brand</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket_component.brand</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_ticket_component.description</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_label_ticket_component.diagnostic</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> DIAGNOSTIC = createField(DSL.name("diagnostic"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_label_ticket_component.id_ticket_state</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_TICKET_STATE = createField(DSL.name("id_ticket_state"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket_component.ticket_state</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> TICKET_STATE = createField(DSL.name("ticket_state"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_ticket_component.date_start</code>.
     */
    public final TableField<VLabelTicketComponentRecord, LocalDateTime> DATE_START = createField(DSL.name("date_start"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_label_ticket_component.date_end</code>.
     */
    public final TableField<VLabelTicketComponentRecord, LocalDateTime> DATE_END = createField(DSL.name("date_end"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_label_ticket_component.id_component</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_COMPONENT = createField(DSL.name("id_component"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.v_label_ticket_component.component_serial_number</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> COMPONENT_SERIAL_NUMBER = createField(DSL.name("component_serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>public.v_label_ticket_component.id_component_category</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_COMPONENT_CATEGORY = createField(DSL.name("id_component_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.v_label_ticket_component.component_category</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> COMPONENT_CATEGORY = createField(DSL.name("component_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column
     * <code>public.v_label_ticket_component.id_component_model</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_COMPONENT_MODEL = createField(DSL.name("id_component_model"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket_component.component_model</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> COMPONENT_MODEL = createField(DSL.name("component_model"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_ticket_component.id_brand2</code>.
     */
    public final TableField<VLabelTicketComponentRecord, Integer> ID_BRAND2 = createField(DSL.name("id_brand2"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_ticket_component.brand2</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> BRAND2 = createField(DSL.name("brand2"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_ticket_component.description2</code>.
     */
    public final TableField<VLabelTicketComponentRecord, String> DESCRIPTION2 = createField(DSL.name("description2"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_label_ticket_component.quantity</code>.
     */
    public final TableField<VLabelTicketComponentRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(13, 2), this, "");

    /**
     * The column <code>public.v_label_ticket_component.cost_total</code>.
     */
    public final TableField<VLabelTicketComponentRecord, BigDecimal> COST_TOTAL = createField(DSL.name("cost_total"), SQLDataType.NUMERIC(13, 2), this, "");

    private VLabelTicketComponent(Name alias, Table<VLabelTicketComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelTicketComponent(Name alias, Table<VLabelTicketComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_ticket_component" as  SELECT tc.id,
         tc.id_ticket,
         t.price_reparation,
         t.id_customer,
         c.name,
         c.telephone,
         c.email,
         c.address,
         t.id_model,
         m.serial_number,
         m.id_model_category,
         mc.label AS model_category,
         m.id_brand,
         b.label AS brand,
         m.description,
         t.diagnostic,
         t.id_ticket_state,
         ts.label AS ticket_state,
         t.date_start,
         t.date_end,
         tc.id_component,
         c2.serial_number AS component_serial_number,
         c2.id_component_category,
         cc.label AS component_category,
         c2.id_model_category AS id_component_model,
         mc2.label AS component_model,
         c2.id_brand AS id_brand2,
         b2.label AS brand2,
         c2.description AS description2,
         tc.quantity,
         tc.cost_total
        FROM ((((((((((ticket_component tc
          JOIN ticket t ON ((tc.id_ticket = t.id)))
          JOIN customer c ON ((t.id_customer = c.id)))
          JOIN model m ON ((t.id_model = m.id)))
          JOIN model_category mc ON ((m.id_model_category = mc.id)))
          JOIN brand b ON ((m.id_brand = b.id)))
          JOIN ticket_state ts ON ((t.id_ticket_state = ts.id)))
          JOIN component c2 ON ((tc.id_component = c2.id)))
          JOIN component_category cc ON ((c2.id_component_category = cc.id)))
          JOIN model_category mc2 ON ((c2.id_model_category = mc2.id)))
          JOIN brand b2 ON ((c2.id_brand = b2.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_ticket_component</code> table
     * reference
     */
    public VLabelTicketComponent(String alias) {
        this(DSL.name(alias), V_LABEL_TICKET_COMPONENT);
    }

    /**
     * Create an aliased <code>public.v_label_ticket_component</code> table
     * reference
     */
    public VLabelTicketComponent(Name alias) {
        this(alias, V_LABEL_TICKET_COMPONENT);
    }

    /**
     * Create a <code>public.v_label_ticket_component</code> table reference
     */
    public VLabelTicketComponent() {
        this(DSL.name("v_label_ticket_component"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelTicketComponent as(String alias) {
        return new VLabelTicketComponent(DSL.name(alias), this);
    }

    @Override
    public VLabelTicketComponent as(Name alias) {
        return new VLabelTicketComponent(alias, this);
    }

    @Override
    public VLabelTicketComponent as(Table<?> alias) {
        return new VLabelTicketComponent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelTicketComponent rename(String name) {
        return new VLabelTicketComponent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelTicketComponent rename(Name name) {
        return new VLabelTicketComponent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelTicketComponent rename(Table<?> name) {
        return new VLabelTicketComponent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicketComponent where(Condition condition) {
        return new VLabelTicketComponent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicketComponent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicketComponent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicketComponent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelTicketComponent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelTicketComponent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelTicketComponent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelTicketComponent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicketComponent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelTicketComponent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
