/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import model.Public;
import model.tables.records.VLabelEntryComponentRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelEntryComponent extends TableImpl<VLabelEntryComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_label_entry_component</code>
     */
    public static final VLabelEntryComponent V_LABEL_ENTRY_COMPONENT = new VLabelEntryComponent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelEntryComponentRecord> getRecordType() {
        return VLabelEntryComponentRecord.class;
    }

    /**
     * The column <code>public.v_label_entry_component.id</code>.
     */
    public final TableField<VLabelEntryComponentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_entry_component.datetime</code>.
     */
    public final TableField<VLabelEntryComponentRecord, LocalDateTime> DATETIME = createField(DSL.name("datetime"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_label_entry_component.quantity</code>.
     */
    public final TableField<VLabelEntryComponentRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(13, 2), this, "");

    /**
     * The column <code>public.v_label_entry_component.cost_unit</code>.
     */
    public final TableField<VLabelEntryComponentRecord, BigDecimal> COST_UNIT = createField(DSL.name("cost_unit"), SQLDataType.NUMERIC(13, 2), this, "");

    /**
     * The column <code>public.v_label_entry_component.id_component</code>.
     */
    public final TableField<VLabelEntryComponentRecord, Integer> ID_COMPONENT = createField(DSL.name("id_component"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_entry_component.serial_number</code>.
     */
    public final TableField<VLabelEntryComponentRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>public.v_label_entry_component.id_component_category</code>.
     */
    public final TableField<VLabelEntryComponentRecord, Integer> ID_COMPONENT_CATEGORY = createField(DSL.name("id_component_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.v_label_entry_component.component_category</code>.
     */
    public final TableField<VLabelEntryComponentRecord, String> COMPONENT_CATEGORY = createField(DSL.name("component_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_entry_component.id_model_category</code>.
     */
    public final TableField<VLabelEntryComponentRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_entry_component.model_category</code>.
     */
    public final TableField<VLabelEntryComponentRecord, String> MODEL_CATEGORY = createField(DSL.name("model_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_entry_component.id_brand</code>.
     */
    public final TableField<VLabelEntryComponentRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_entry_component.brand</code>.
     */
    public final TableField<VLabelEntryComponentRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_entry_component.description</code>.
     */
    public final TableField<VLabelEntryComponentRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_label_entry_component.id_supplier</code>.
     */
    public final TableField<VLabelEntryComponentRecord, Integer> ID_SUPPLIER = createField(DSL.name("id_supplier"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_entry_component.name</code>.
     */
    public final TableField<VLabelEntryComponentRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_entry_component.telephone</code>.
     */
    public final TableField<VLabelEntryComponentRecord, String> TELEPHONE = createField(DSL.name("telephone"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.v_label_entry_component.email</code>.
     */
    public final TableField<VLabelEntryComponentRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_entry_component.address</code>.
     */
    public final TableField<VLabelEntryComponentRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "");

    private VLabelEntryComponent(Name alias, Table<VLabelEntryComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelEntryComponent(Name alias, Table<VLabelEntryComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_entry_component" as  SELECT ec.id,
         ec.datetime,
         ec.quantity,
         ec.cost_unit,
         ec.id_component,
         c.serial_number,
         c.id_component_category,
         cc.label AS component_category,
         c.id_model_category,
         mc.label AS model_category,
         c.id_brand,
         b.label AS brand,
         c.description,
         ec.id_supplier,
         s.name,
         s.telephone,
         s.email,
         s.address
        FROM (((((entry_component ec
          JOIN component c ON ((ec.id_component = c.id)))
          JOIN component_category cc ON ((c.id_component_category = cc.id)))
          JOIN model_category mc ON ((c.id_model_category = mc.id)))
          JOIN brand b ON ((c.id_brand = b.id)))
          JOIN supplier s ON ((ec.id_supplier = s.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_entry_component</code> table
     * reference
     */
    public VLabelEntryComponent(String alias) {
        this(DSL.name(alias), V_LABEL_ENTRY_COMPONENT);
    }

    /**
     * Create an aliased <code>public.v_label_entry_component</code> table
     * reference
     */
    public VLabelEntryComponent(Name alias) {
        this(alias, V_LABEL_ENTRY_COMPONENT);
    }

    /**
     * Create a <code>public.v_label_entry_component</code> table reference
     */
    public VLabelEntryComponent() {
        this(DSL.name("v_label_entry_component"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelEntryComponent as(String alias) {
        return new VLabelEntryComponent(DSL.name(alias), this);
    }

    @Override
    public VLabelEntryComponent as(Name alias) {
        return new VLabelEntryComponent(alias, this);
    }

    @Override
    public VLabelEntryComponent as(Table<?> alias) {
        return new VLabelEntryComponent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelEntryComponent rename(String name) {
        return new VLabelEntryComponent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelEntryComponent rename(Name name) {
        return new VLabelEntryComponent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelEntryComponent rename(Table<?> name) {
        return new VLabelEntryComponent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelEntryComponent where(Condition condition) {
        return new VLabelEntryComponent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelEntryComponent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelEntryComponent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelEntryComponent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelEntryComponent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelEntryComponent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelEntryComponent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelEntryComponent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelEntryComponent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelEntryComponent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
