/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.time.LocalDate;
import java.util.Collection;

import model.Public;
import model.tables.records.VLabelRecommendationComponentRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelRecommendationComponent extends TableImpl<VLabelRecommendationComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.v_label_recommendation_component</code>
     */
    public static final VLabelRecommendationComponent V_LABEL_RECOMMENDATION_COMPONENT = new VLabelRecommendationComponent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelRecommendationComponentRecord> getRecordType() {
        return VLabelRecommendationComponentRecord.class;
    }

    /**
     * The column
     * <code>public.v_label_recommendation_component.date_start</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, LocalDate> DATE_START = createField(DSL.name("date_start"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.v_label_recommendation_component.date_end</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, LocalDate> DATE_END = createField(DSL.name("date_end"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.v_label_recommendation_component.id</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.v_label_recommendation_component.serial_number</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>public.v_label_recommendation_component.id_component_category</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, Integer> ID_COMPONENT_CATEGORY = createField(DSL.name("id_component_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.v_label_recommendation_component.component_category</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, String> COMPONENT_CATEGORY = createField(DSL.name("component_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column
     * <code>public.v_label_recommendation_component.id_model_category</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, Integer> ID_MODEL_CATEGORY = createField(DSL.name("id_model_category"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.v_label_recommendation_component.model_category</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, String> MODEL_CATEGORY = createField(DSL.name("model_category"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_label_recommendation_component.id_brand</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, Integer> ID_BRAND = createField(DSL.name("id_brand"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_recommendation_component.brand</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column
     * <code>public.v_label_recommendation_component.description</code>.
     */
    public final TableField<VLabelRecommendationComponentRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private VLabelRecommendationComponent(Name alias, Table<VLabelRecommendationComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelRecommendationComponent(Name alias, Table<VLabelRecommendationComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_recommendation_component" as  SELECT rec.date_start,
         rec.date_end,
         v.id,
         v.serial_number,
         v.id_component_category,
         v.component_category,
         v.id_model_category,
         v.model_category,
         v.id_brand,
         v.brand,
         v.description
        FROM (recommendation_component rec
          JOIN v_label_component v ON ((rec.id_component = v.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_recommendation_component</code>
     * table reference
     */
    public VLabelRecommendationComponent(String alias) {
        this(DSL.name(alias), V_LABEL_RECOMMENDATION_COMPONENT);
    }

    /**
     * Create an aliased <code>public.v_label_recommendation_component</code>
     * table reference
     */
    public VLabelRecommendationComponent(Name alias) {
        this(alias, V_LABEL_RECOMMENDATION_COMPONENT);
    }

    /**
     * Create a <code>public.v_label_recommendation_component</code> table
     * reference
     */
    public VLabelRecommendationComponent() {
        this(DSL.name("v_label_recommendation_component"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelRecommendationComponent as(String alias) {
        return new VLabelRecommendationComponent(DSL.name(alias), this);
    }

    @Override
    public VLabelRecommendationComponent as(Name alias) {
        return new VLabelRecommendationComponent(alias, this);
    }

    @Override
    public VLabelRecommendationComponent as(Table<?> alias) {
        return new VLabelRecommendationComponent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelRecommendationComponent rename(String name) {
        return new VLabelRecommendationComponent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelRecommendationComponent rename(Name name) {
        return new VLabelRecommendationComponent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelRecommendationComponent rename(Table<?> name) {
        return new VLabelRecommendationComponent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelRecommendationComponent where(Condition condition) {
        return new VLabelRecommendationComponent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelRecommendationComponent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelRecommendationComponent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelRecommendationComponent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelRecommendationComponent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelRecommendationComponent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelRecommendationComponent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelRecommendationComponent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelRecommendationComponent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelRecommendationComponent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
