/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import model.Public;
import model.tables.records.VStateMvtTicketStateRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VStateMvtTicketState extends TableImpl<VStateMvtTicketStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_state_mvt_ticket_state</code>
     */
    public static final VStateMvtTicketState V_STATE_MVT_TICKET_STATE = new VStateMvtTicketState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VStateMvtTicketStateRecord> getRecordType() {
        return VStateMvtTicketStateRecord.class;
    }

    /**
     * The column <code>public.v_state_mvt_ticket_state.id</code>.
     */
    public final TableField<VStateMvtTicketStateRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_state_mvt_ticket_state.datetime</code>.
     */
    public final TableField<VStateMvtTicketStateRecord, LocalDateTime> DATETIME = createField(DSL.name("datetime"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_state_mvt_ticket_state.id_ticket</code>.
     */
    public final TableField<VStateMvtTicketStateRecord, Integer> ID_TICKET = createField(DSL.name("id_ticket"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_state_mvt_ticket_state.id_ticket_state</code>.
     */
    public final TableField<VStateMvtTicketStateRecord, Integer> ID_TICKET_STATE = createField(DSL.name("id_ticket_state"), SQLDataType.INTEGER, this, "");

    private VStateMvtTicketState(Name alias, Table<VStateMvtTicketStateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VStateMvtTicketState(Name alias, Table<VStateMvtTicketStateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_state_mvt_ticket_state" as  SELECT mts.id,
         mts.datetime,
         mts.id_ticket,
         mts.id_ticket_state
        FROM (mvt_ticket_state mts
          JOIN ( SELECT max(_mts.datetime) AS datetime,
                 _mts.id_ticket
                FROM mvt_ticket_state _mts
               GROUP BY _mts.id_ticket) mts_state ON (((mts.datetime = mts_state.datetime) AND (mts.id_ticket = mts_state.id_ticket))));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_state_mvt_ticket_state</code> table
     * reference
     */
    public VStateMvtTicketState(String alias) {
        this(DSL.name(alias), V_STATE_MVT_TICKET_STATE);
    }

    /**
     * Create an aliased <code>public.v_state_mvt_ticket_state</code> table
     * reference
     */
    public VStateMvtTicketState(Name alias) {
        this(alias, V_STATE_MVT_TICKET_STATE);
    }

    /**
     * Create a <code>public.v_state_mvt_ticket_state</code> table reference
     */
    public VStateMvtTicketState() {
        this(DSL.name("v_state_mvt_ticket_state"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VStateMvtTicketState as(String alias) {
        return new VStateMvtTicketState(DSL.name(alias), this);
    }

    @Override
    public VStateMvtTicketState as(Name alias) {
        return new VStateMvtTicketState(alias, this);
    }

    @Override
    public VStateMvtTicketState as(Table<?> alias) {
        return new VStateMvtTicketState(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VStateMvtTicketState rename(String name) {
        return new VStateMvtTicketState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VStateMvtTicketState rename(Name name) {
        return new VStateMvtTicketState(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VStateMvtTicketState rename(Table<?> name) {
        return new VStateMvtTicketState(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VStateMvtTicketState where(Condition condition) {
        return new VStateMvtTicketState(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VStateMvtTicketState where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VStateMvtTicketState where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VStateMvtTicketState where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VStateMvtTicketState where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VStateMvtTicketState where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VStateMvtTicketState where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VStateMvtTicketState where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VStateMvtTicketState whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VStateMvtTicketState whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
