/*
 * This file is generated by jOOQ.
 */
package model;


import java.util.Arrays;
import java.util.List;

import model.tables.Brand;
import model.tables.Component;
import model.tables.ComponentCategory;
import model.tables.Model;
import model.tables.ModelCategory;
import model.tables.VLabelComponent;
import model.tables.VLabelModel;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.brand</code>.
     */
    public final Brand BRAND = Brand.BRAND;

    /**
     * The table <code>public.component</code>.
     */
    public final Component COMPONENT = Component.COMPONENT;

    /**
     * The table <code>public.component_category</code>.
     */
    public final ComponentCategory COMPONENT_CATEGORY = ComponentCategory.COMPONENT_CATEGORY;

    /**
     * The table <code>public.model</code>.
     */
    public final Model MODEL = Model.MODEL;

    /**
     * The table <code>public.model_category</code>.
     */
    public final ModelCategory MODEL_CATEGORY = ModelCategory.MODEL_CATEGORY;

    /**
     * The table <code>public.v_label_component</code>.
     */
    public final VLabelComponent V_LABEL_COMPONENT = VLabelComponent.V_LABEL_COMPONENT;

    /**
     * The table <code>public.v_label_model</code>.
     */
    public final VLabelModel V_LABEL_MODEL = VLabelModel.V_LABEL_MODEL;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Brand.BRAND,
            Component.COMPONENT,
            ComponentCategory.COMPONENT_CATEGORY,
            Model.MODEL,
            ModelCategory.MODEL_CATEGORY,
            VLabelComponent.V_LABEL_COMPONENT,
            VLabelModel.V_LABEL_MODEL
        );
    }
}
