/*
 * This file is generated by jOOQ.
 */
package model;


import model.routines.PStateMvtTicketState;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>public.p_state_mvt_ticket_state</code>
     */
    public static Integer pStateMvtTicketState(
          Configuration configuration
        , Integer idTicketParam
    ) {
        PStateMvtTicketState p = new PStateMvtTicketState();
        p.setIdTicketParam(idTicketParam);

        p.execute(configuration);
        return p.getIdTicketStatusOutput();
    }
}
