/*
 * This file is generated by jOOQ.
 */
package model;


import model.tables.Brand;
import model.tables.Component;
import model.tables.ComponentCategory;
import model.tables.Customer;
import model.tables.Engineer;
import model.tables.Gender;
import model.tables.Model;
import model.tables.ModelCategory;
import model.tables.MvtTicketState;
import model.tables.RecommendationComponent;
import model.tables.Reparation;
import model.tables.ReparationDetail;
import model.tables.ReparationFeedback;
import model.tables.Ticket;
import model.tables.TicketComponent;
import model.tables.TicketState;
import model.tables.VEngineerCommission;
import model.tables.VLabelComponent;
import model.tables.VLabelModel;
import model.tables.VLabelRecommendationComponent;
import model.tables.VLabelReparation;
import model.tables.VLabelTicket;
import model.tables.VStateMvtTicketState;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.brand</code>.
     */
    public static final Brand BRAND = Brand.BRAND;

    /**
     * The table <code>public.component</code>.
     */
    public static final Component COMPONENT = Component.COMPONENT;

    /**
     * The table <code>public.component_category</code>.
     */
    public static final ComponentCategory COMPONENT_CATEGORY = ComponentCategory.COMPONENT_CATEGORY;

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.engineer</code>.
     */
    public static final Engineer ENGINEER = Engineer.ENGINEER;

    /**
     * The table <code>public.gender</code>.
     */
    public static final Gender GENDER = Gender.GENDER;

    /**
     * The table <code>public.model</code>.
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * The table <code>public.model_category</code>.
     */
    public static final ModelCategory MODEL_CATEGORY = ModelCategory.MODEL_CATEGORY;

    /**
     * The table <code>public.mvt_ticket_state</code>.
     */
    public static final MvtTicketState MVT_TICKET_STATE = MvtTicketState.MVT_TICKET_STATE;

    /**
     * The table <code>public.recommendation_component</code>.
     */
    public static final RecommendationComponent RECOMMENDATION_COMPONENT = RecommendationComponent.RECOMMENDATION_COMPONENT;

    /**
     * The table <code>public.reparation</code>.
     */
    public static final Reparation REPARATION = Reparation.REPARATION;

    /**
     * The table <code>public.reparation_detail</code>.
     */
    public static final ReparationDetail REPARATION_DETAIL = ReparationDetail.REPARATION_DETAIL;

    /**
     * The table <code>public.reparation_feedback</code>.
     */
    public static final ReparationFeedback REPARATION_FEEDBACK = ReparationFeedback.REPARATION_FEEDBACK;

    /**
     * The table <code>public.ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>public.ticket_component</code>.
     */
    public static final TicketComponent TICKET_COMPONENT = TicketComponent.TICKET_COMPONENT;

    /**
     * The table <code>public.ticket_state</code>.
     */
    public static final TicketState TICKET_STATE = TicketState.TICKET_STATE;

    /**
     * The table <code>public.v_engineer_commission</code>.
     */
    public static final VEngineerCommission V_ENGINEER_COMMISSION = VEngineerCommission.V_ENGINEER_COMMISSION;

    /**
     * The table <code>public.v_label_component</code>.
     */
    public static final VLabelComponent V_LABEL_COMPONENT = VLabelComponent.V_LABEL_COMPONENT;

    /**
     * The table <code>public.v_label_model</code>.
     */
    public static final VLabelModel V_LABEL_MODEL = VLabelModel.V_LABEL_MODEL;

    /**
     * The table <code>public.v_label_recommendation_component</code>.
     */
    public static final VLabelRecommendationComponent V_LABEL_RECOMMENDATION_COMPONENT = VLabelRecommendationComponent.V_LABEL_RECOMMENDATION_COMPONENT;

    /**
     * The table <code>public.v_label_reparation</code>.
     */
    public static final VLabelReparation V_LABEL_REPARATION = VLabelReparation.V_LABEL_REPARATION;

    /**
     * The table <code>public.v_label_ticket</code>.
     */
    public static final VLabelTicket V_LABEL_TICKET = VLabelTicket.V_LABEL_TICKET;

    /**
     * The table <code>public.v_state_mvt_ticket_state</code>.
     */
    public static final VStateMvtTicketState V_STATE_MVT_TICKET_STATE = VStateMvtTicketState.V_STATE_MVT_TICKET_STATE;
}
