/*
 * This file is generated by jOOQ.
 */
package model;


import model.tables.Brand;
import model.tables.Component;
import model.tables.ComponentCategory;
import model.tables.Customer;
import model.tables.Engineer;
<<<<<<< HEAD
import model.tables.EntryComponent;
=======
>>>>>>> 7b555d5371200f884cecf79ce7f9b91e91d53d06
import model.tables.Model;
import model.tables.ModelCategory;
import model.tables.MvtStockComponent;
import model.tables.MvtTicketState;
import model.tables.RecommendationComponent;
import model.tables.Reparation;
import model.tables.ReparationDetail;
import model.tables.ReparationFeedback;
<<<<<<< HEAD
import model.tables.Supplier;
import model.tables.Ticket;
import model.tables.TicketComponent;
import model.tables.TicketState;
import model.tables.TicketStockWithdraw;
=======
>>>>>>> 7b555d5371200f884cecf79ce7f9b91e91d53d06
import model.tables.VEngineerCommission;
import model.tables.VLabelComponent;
import model.tables.VLabelEntryComponent;
import model.tables.VLabelModel;
import model.tables.VLabelMvtStockComponent;
import model.tables.VLabelRecommendationComponent;
import model.tables.VLabelReparation;
<<<<<<< HEAD
import model.tables.VLabelReparationFeedback;
import model.tables.VLabelTicket;
import model.tables.VStateMvtTicketState;
=======
>>>>>>> 7b555d5371200f884cecf79ce7f9b91e91d53d06


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.brand</code>.
     */
    public static final Brand BRAND = Brand.BRAND;

    /**
     * The table <code>public.component</code>.
     */
    public static final Component COMPONENT = Component.COMPONENT;

    /**
     * The table <code>public.component_category</code>.
     */
    public static final ComponentCategory COMPONENT_CATEGORY = ComponentCategory.COMPONENT_CATEGORY;

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.engineer</code>.
     */
    public static final Engineer ENGINEER = Engineer.ENGINEER;

    /**
<<<<<<< HEAD
     * The table <code>public.entry_component</code>.
     */
    public static final EntryComponent ENTRY_COMPONENT = EntryComponent.ENTRY_COMPONENT;

    /**
=======
>>>>>>> 7b555d5371200f884cecf79ce7f9b91e91d53d06
     * The table <code>public.model</code>.
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * The table <code>public.model_category</code>.
     */
    public static final ModelCategory MODEL_CATEGORY = ModelCategory.MODEL_CATEGORY;

    /**
     * The table <code>public.mvt_stock_component</code>.
     */
    public static final MvtStockComponent MVT_STOCK_COMPONENT = MvtStockComponent.MVT_STOCK_COMPONENT;

    /**
     * The table <code>public.mvt_ticket_state</code>.
     */
    public static final MvtTicketState MVT_TICKET_STATE = MvtTicketState.MVT_TICKET_STATE;

    /**
     * The table <code>public.recommendation_component</code>.
     */
    public static final RecommendationComponent RECOMMENDATION_COMPONENT = RecommendationComponent.RECOMMENDATION_COMPONENT;

    /**
     * The table <code>public.reparation</code>.
     */
    public static final Reparation REPARATION = Reparation.REPARATION;

    /**
     * The table <code>public.reparation_detail</code>.
     */
    public static final ReparationDetail REPARATION_DETAIL = ReparationDetail.REPARATION_DETAIL;

    /**
     * The table <code>public.reparation_feedback</code>.
     */
    public static final ReparationFeedback REPARATION_FEEDBACK = ReparationFeedback.REPARATION_FEEDBACK;

    /**
<<<<<<< HEAD
     * The table <code>public.supplier</code>.
     */
    public static final Supplier SUPPLIER = Supplier.SUPPLIER;

    /**
     * The table <code>public.ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>public.ticket_component</code>.
     */
    public static final TicketComponent TICKET_COMPONENT = TicketComponent.TICKET_COMPONENT;

    /**
     * The table <code>public.ticket_state</code>.
     */
    public static final TicketState TICKET_STATE = TicketState.TICKET_STATE;

    /**
     * The table <code>public.ticket_stock_withdraw</code>.
     */
    public static final TicketStockWithdraw TICKET_STOCK_WITHDRAW = TicketStockWithdraw.TICKET_STOCK_WITHDRAW;

    /**
=======
>>>>>>> 7b555d5371200f884cecf79ce7f9b91e91d53d06
     * The table <code>public.v_engineer_commission</code>.
     */
    public static final VEngineerCommission V_ENGINEER_COMMISSION = VEngineerCommission.V_ENGINEER_COMMISSION;

    /**
     * The table <code>public.v_label_component</code>.
     */
    public static final VLabelComponent V_LABEL_COMPONENT = VLabelComponent.V_LABEL_COMPONENT;

    /**
     * The table <code>public.v_label_entry_component</code>.
     */
    public static final VLabelEntryComponent V_LABEL_ENTRY_COMPONENT = VLabelEntryComponent.V_LABEL_ENTRY_COMPONENT;

    /**
     * The table <code>public.v_label_model</code>.
     */
    public static final VLabelModel V_LABEL_MODEL = VLabelModel.V_LABEL_MODEL;

    /**
     * The table <code>public.v_label_mvt_stock_component</code>.
     */
    public static final VLabelMvtStockComponent V_LABEL_MVT_STOCK_COMPONENT = VLabelMvtStockComponent.V_LABEL_MVT_STOCK_COMPONENT;

    /**
     * The table <code>public.v_label_recommendation_component</code>.
     */
    public static final VLabelRecommendationComponent V_LABEL_RECOMMENDATION_COMPONENT = VLabelRecommendationComponent.V_LABEL_RECOMMENDATION_COMPONENT;

    /**
     * The table <code>public.v_label_reparation</code>.
     */
    public static final VLabelReparation V_LABEL_REPARATION = VLabelReparation.V_LABEL_REPARATION;
<<<<<<< HEAD

    /**
     * The table <code>public.v_label_reparation_feedback</code>.
     */
    public static final VLabelReparationFeedback V_LABEL_REPARATION_FEEDBACK = VLabelReparationFeedback.V_LABEL_REPARATION_FEEDBACK;

    /**
     * The table <code>public.v_label_ticket</code>.
     */
    public static final VLabelTicket V_LABEL_TICKET = VLabelTicket.V_LABEL_TICKET;

    /**
     * The table <code>public.v_state_mvt_ticket_state</code>.
     */
    public static final VStateMvtTicketState V_STATE_MVT_TICKET_STATE = VStateMvtTicketState.V_STATE_MVT_TICKET_STATE;
=======
>>>>>>> 7b555d5371200f884cecf79ce7f9b91e91d53d06
}
