/*
 * This file is generated by jOOQ.
 */
package model;


import model.tables.Brand;
import model.tables.Component;
import model.tables.ComponentCategory;
import model.tables.Model;
import model.tables.ModelCategory;
import model.tables.Reparation;
import model.tables.ReparationDetail;
import model.tables.ReparationFeedback;
import model.tables.VLabelComponent;
import model.tables.VLabelModel;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.brand</code>.
     */
    public static final Brand BRAND = Brand.BRAND;

    /**
     * The table <code>public.component</code>.
     */
    public static final Component COMPONENT = Component.COMPONENT;

    /**
     * The table <code>public.component_category</code>.
     */
    public static final ComponentCategory COMPONENT_CATEGORY = ComponentCategory.COMPONENT_CATEGORY;

    /**
     * The table <code>public.model</code>.
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * The table <code>public.model_category</code>.
     */
    public static final ModelCategory MODEL_CATEGORY = ModelCategory.MODEL_CATEGORY;

    /**
     * The table <code>public.reparation</code>.
     */
    public static final Reparation REPARATION = Reparation.REPARATION;

    /**
     * The table <code>public.reparation_detail</code>.
     */
    public static final ReparationDetail REPARATION_DETAIL = ReparationDetail.REPARATION_DETAIL;

    /**
     * The table <code>public.reparation_feedback</code>.
     */
    public static final ReparationFeedback REPARATION_FEEDBACK = ReparationFeedback.REPARATION_FEEDBACK;

    /**
     * The table <code>public.v_label_component</code>.
     */
    public static final VLabelComponent V_LABEL_COMPONENT = VLabelComponent.V_LABEL_COMPONENT;

    /**
     * The table <code>public.v_label_model</code>.
     */
    public static final VLabelModel V_LABEL_MODEL = VLabelModel.V_LABEL_MODEL;
}
