/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import model.tables.Component;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ComponentRecord extends UpdatableRecordImpl<ComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.component.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.component.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.component.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.component.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.component.id_component_category</code>.
     */
    public void setIdComponentCategory(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.component.id_component_category</code>.
     */
    public Integer getIdComponentCategory() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.component.id_model_category</code>.
     */
    public void setIdModelCategory(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.component.id_model_category</code>.
     */
    public Integer getIdModelCategory() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.component.id_brand</code>.
     */
    public void setIdBrand(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.component.id_brand</code>.
     */
    public Integer getIdBrand() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.component.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.component.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComponentRecord
     */
    public ComponentRecord() {
        super(Component.COMPONENT);
    }

    /**
     * Create a detached, initialised ComponentRecord
     */
    public ComponentRecord(Integer id, String serialNumber, Integer idComponentCategory, Integer idModelCategory, Integer idBrand, String description) {
        super(Component.COMPONENT);

        setId(id);
        setSerialNumber(serialNumber);
        setIdComponentCategory(idComponentCategory);
        setIdModelCategory(idModelCategory);
        setIdBrand(idBrand);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
