/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import model.tables.ComponentCategory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ComponentCategoryRecord extends UpdatableRecordImpl<ComponentCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.component_category.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.component_category.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.component_category.label</code>.
     */
    public void setLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.component_category.label</code>.
     */
    public String getLabel() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComponentCategoryRecord
     */
    public ComponentCategoryRecord() {
        super(ComponentCategory.COMPONENT_CATEGORY);
    }

    /**
     * Create a detached, initialised ComponentCategoryRecord
     */
    public ComponentCategoryRecord(Integer id, String label) {
        super(ComponentCategory.COMPONENT_CATEGORY);

        setId(id);
        setLabel(label);
        resetChangedOnNotNull();
    }
}
