/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import model.tables.Engineer;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EngineerRecord extends UpdatableRecordImpl<EngineerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.engineer.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.engineer.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.engineer.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.engineer.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.engineer.telephone</code>.
     */
    public void setTelephone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.engineer.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.engineer.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.engineer.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.engineer.address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.engineer.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.engineer.id_gender</code>.
     */
    public void setIdGender(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.engineer.id_gender</code>.
     */
    public Integer getIdGender() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EngineerRecord
     */
    public EngineerRecord() {
        super(Engineer.ENGINEER);
    }

    /**
     * Create a detached, initialised EngineerRecord
     */
    public EngineerRecord(Integer id, String name, String telephone, String email, String address, Integer idGender) {
        super(Engineer.ENGINEER);

        setId(id);
        setName(name);
        setTelephone(telephone);
        setEmail(email);
        setAddress(address);
        setIdGender(idGender);
        resetChangedOnNotNull();
    }
}
