/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import model.tables.EntryComponent;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EntryComponentRecord extends UpdatableRecordImpl<EntryComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.entry_component.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.entry_component.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.entry_component.datetime</code>.
     */
    public void setDatetime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.entry_component.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.entry_component.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.entry_component.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.entry_component.cost_unit</code>.
     */
    public void setCostUnit(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.entry_component.cost_unit</code>.
     */
    public BigDecimal getCostUnit() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.entry_component.id_component</code>.
     */
    public void setIdComponent(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.entry_component.id_component</code>.
     */
    public Integer getIdComponent() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.entry_component.id_supplier</code>.
     */
    public void setIdSupplier(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.entry_component.id_supplier</code>.
     */
    public Integer getIdSupplier() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntryComponentRecord
     */
    public EntryComponentRecord() {
        super(EntryComponent.ENTRY_COMPONENT);
    }

    /**
     * Create a detached, initialised EntryComponentRecord
     */
    public EntryComponentRecord(Integer id, LocalDateTime datetime, BigDecimal quantity, BigDecimal costUnit, Integer idComponent, Integer idSupplier) {
        super(EntryComponent.ENTRY_COMPONENT);

        setId(id);
        setDatetime(datetime);
        setQuantity(quantity);
        setCostUnit(costUnit);
        setIdComponent(idComponent);
        setIdSupplier(idSupplier);
        resetChangedOnNotNull();
    }
}
