/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import model.tables.Gender;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GenderRecord extends UpdatableRecordImpl<GenderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.gender.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.gender.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.gender.gender</code>.
     */
    public void setGender(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.gender.gender</code>.
     */
    public String getGender() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GenderRecord
     */
    public GenderRecord() {
        super(Gender.GENDER);
    }

    /**
     * Create a detached, initialised GenderRecord
     */
    public GenderRecord(Integer id, String gender) {
        super(Gender.GENDER);

        setId(id);
        setGender(gender);
        resetChangedOnNotNull();
    }
}
