/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import model.tables.Model;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ModelRecord extends UpdatableRecordImpl<ModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.model.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.model.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.model.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.model.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.model.id_model_category</code>.
     */
    public void setIdModelCategory(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.model.id_model_category</code>.
     */
    public Integer getIdModelCategory() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.model.id_brand</code>.
     */
    public void setIdBrand(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.model.id_brand</code>.
     */
    public Integer getIdBrand() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.model.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.model.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelRecord
     */
    public ModelRecord() {
        super(Model.MODEL);
    }

    /**
     * Create a detached, initialised ModelRecord
     */
    public ModelRecord(Integer id, String serialNumber, Integer idModelCategory, Integer idBrand, String description) {
        super(Model.MODEL);

        setId(id);
        setSerialNumber(serialNumber);
        setIdModelCategory(idModelCategory);
        setIdBrand(idBrand);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
