/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.math.BigDecimal;

import model.tables.MvtStockComponent;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MvtStockComponentRecord extends UpdatableRecordImpl<MvtStockComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mvt_stock_component.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mvt_stock_component.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.mvt_stock_component.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mvt_stock_component.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.mvt_stock_component.cost_unit</code>.
     */
    public void setCostUnit(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mvt_stock_component.cost_unit</code>.
     */
    public BigDecimal getCostUnit() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.mvt_stock_component.id_component</code>.
     */
    public void setIdComponent(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mvt_stock_component.id_component</code>.
     */
    public Integer getIdComponent() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MvtStockComponentRecord
     */
    public MvtStockComponentRecord() {
        super(MvtStockComponent.MVT_STOCK_COMPONENT);
    }

    /**
     * Create a detached, initialised MvtStockComponentRecord
     */
    public MvtStockComponentRecord(Integer id, BigDecimal quantity, BigDecimal costUnit, Integer idComponent) {
        super(MvtStockComponent.MVT_STOCK_COMPONENT);

        setId(id);
        setQuantity(quantity);
        setCostUnit(costUnit);
        setIdComponent(idComponent);
        resetChangedOnNotNull();
    }
}
