/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDateTime;

import model.tables.MvtTicketState;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MvtTicketStateRecord extends UpdatableRecordImpl<MvtTicketStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mvt_ticket_state.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mvt_ticket_state.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.mvt_ticket_state.datetime</code>.
     */
    public void setDatetime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mvt_ticket_state.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.mvt_ticket_state.id_ticket</code>.
     */
    public void setIdTicket(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mvt_ticket_state.id_ticket</code>.
     */
    public Integer getIdTicket() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.mvt_ticket_state.id_ticket_state</code>.
     */
    public void setIdTicketState(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mvt_ticket_state.id_ticket_state</code>.
     */
    public Integer getIdTicketState() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MvtTicketStateRecord
     */
    public MvtTicketStateRecord() {
        super(MvtTicketState.MVT_TICKET_STATE);
    }

    /**
     * Create a detached, initialised MvtTicketStateRecord
     */
    public MvtTicketStateRecord(Integer id, LocalDateTime datetime, Integer idTicket, Integer idTicketState) {
        super(MvtTicketState.MVT_TICKET_STATE);

        setId(id);
        setDatetime(datetime);
        setIdTicket(idTicket);
        setIdTicketState(idTicketState);
        resetChangedOnNotNull();
    }
}
