/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDate;

import model.tables.RecommendationComponent;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecommendationComponentRecord extends UpdatableRecordImpl<RecommendationComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.recommendation_component.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.recommendation_component.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.recommendation_component.id_component</code>.
     */
    public void setIdComponent(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.recommendation_component.id_component</code>.
     */
    public Integer getIdComponent() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.recommendation_component.date_start</code>.
     */
    public void setDateStart(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.recommendation_component.date_start</code>.
     */
    public LocalDate getDateStart() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.recommendation_component.date_end</code>.
     */
    public void setDateEnd(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.recommendation_component.date_end</code>.
     */
    public LocalDate getDateEnd() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecommendationComponentRecord
     */
    public RecommendationComponentRecord() {
        super(RecommendationComponent.RECOMMENDATION_COMPONENT);
    }

    /**
     * Create a detached, initialised RecommendationComponentRecord
     */
    public RecommendationComponentRecord(Integer id, Integer idComponent, LocalDate dateStart, LocalDate dateEnd) {
        super(RecommendationComponent.RECOMMENDATION_COMPONENT);

        setId(id);
        setIdComponent(idComponent);
        setDateStart(dateStart);
        setDateEnd(dateEnd);
        resetChangedOnNotNull();
    }
}
