/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import model.tables.ReparationDetail;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReparationDetailRecord extends UpdatableRecordImpl<ReparationDetailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reparation_detail.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reparation_detail.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.reparation_detail.id_reparation</code>.
     */
    public void setIdReparation(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reparation_detail.id_reparation</code>.
     */
    public Integer getIdReparation() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.reparation_detail.id_component_category</code>.
     */
    public void setIdComponentCategory(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reparation_detail.id_component_category</code>.
     */
    public Integer getIdComponentCategory() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReparationDetailRecord
     */
    public ReparationDetailRecord() {
        super(ReparationDetail.REPARATION_DETAIL);
    }

    /**
     * Create a detached, initialised ReparationDetailRecord
     */
    public ReparationDetailRecord(Integer id, Integer idReparation, Integer idComponentCategory) {
        super(ReparationDetail.REPARATION_DETAIL);

        setId(id);
        setIdReparation(idReparation);
        setIdComponentCategory(idComponentCategory);
        resetChangedOnNotNull();
    }
}
