/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDate;

import model.tables.ReparationFeedback;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReparationFeedbackRecord extends UpdatableRecordImpl<ReparationFeedbackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reparation_feedback.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reparation_feedback.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.reparation_feedback.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reparation_feedback.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.reparation_feedback.id_customer</code>.
     */
    public void setIdCustomer(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reparation_feedback.id_customer</code>.
     */
    public Integer getIdCustomer() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.reparation_feedback.id_reparation</code>.
     */
    public void setIdReparation(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.reparation_feedback.id_reparation</code>.
     */
    public Integer getIdReparation() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReparationFeedbackRecord
     */
    public ReparationFeedbackRecord() {
        super(ReparationFeedback.REPARATION_FEEDBACK);
    }

    /**
     * Create a detached, initialised ReparationFeedbackRecord
     */
    public ReparationFeedbackRecord(Integer id, LocalDate date, Integer idCustomer, Integer idReparation) {
        super(ReparationFeedback.REPARATION_FEEDBACK);

        setId(id);
        setDate(date);
        setIdCustomer(idCustomer);
        setIdReparation(idReparation);
        resetChangedOnNotNull();
    }
}
