/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDate;

import model.tables.Reparation;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReparationRecord extends UpdatableRecordImpl<ReparationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reparation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reparation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.reparation.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reparation.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.reparation.price</code>.
     */
    public void setPrice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reparation.price</code>.
     */
    public Double getPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.reparation.id_model</code>.
     */
    public void setIdModel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.reparation.id_model</code>.
     */
    public Integer getIdModel() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReparationRecord
     */
    public ReparationRecord() {
        super(Reparation.REPARATION);
    }

    /**
     * Create a detached, initialised ReparationRecord
     */
    public ReparationRecord(Integer id, LocalDate date, Double price, Integer idModel) {
        super(Reparation.REPARATION);

        setId(id);
        setDate(date);
        setPrice(price);
        setIdModel(idModel);
        resetChangedOnNotNull();
    }
}
