/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.math.BigDecimal;

import model.tables.TicketStockWithdraw;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TicketStockWithdrawRecord extends UpdatableRecordImpl<TicketStockWithdrawRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ticket_stock_withdraw.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ticket_stock_withdraw.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ticket_stock_withdraw.id_ticket</code>.
     */
    public void setIdTicket(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ticket_stock_withdraw.id_ticket</code>.
     */
    public Integer getIdTicket() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.ticket_stock_withdraw.id_entry_component</code>.
     */
    public void setIdEntryComponent(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ticket_stock_withdraw.id_entry_component</code>.
     */
    public Integer getIdEntryComponent() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.ticket_stock_withdraw.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ticket_stock_withdraw.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketStockWithdrawRecord
     */
    public TicketStockWithdrawRecord() {
        super(TicketStockWithdraw.TICKET_STOCK_WITHDRAW);
    }

    /**
     * Create a detached, initialised TicketStockWithdrawRecord
     */
    public TicketStockWithdrawRecord(Integer id, Integer idTicket, Integer idEntryComponent, BigDecimal quantity) {
        super(TicketStockWithdraw.TICKET_STOCK_WITHDRAW);

        setId(id);
        setIdTicket(idTicket);
        setIdEntryComponent(idEntryComponent);
        setQuantity(quantity);
        resetChangedOnNotNull();
    }
}
