/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import model.tables.TicketState;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TicketStateRecord extends UpdatableRecordImpl<TicketStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ticket_state.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ticket_state.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ticket_state.label</code>.
     */
    public void setLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ticket_state.label</code>.
     */
    public String getLabel() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketStateRecord
     */
    public TicketStateRecord() {
        super(TicketState.TICKET_STATE);
    }

    /**
     * Create a detached, initialised TicketStateRecord
     */
    public TicketStateRecord(Integer id, String label) {
        super(TicketState.TICKET_STATE);

        setId(id);
        setLabel(label);
        resetChangedOnNotNull();
    }
}
