/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.math.BigDecimal;

import model.tables.TicketComponent;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TicketComponentRecord extends UpdatableRecordImpl<TicketComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ticket_component.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ticket_component.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ticket_component.id_ticket</code>.
     */
    public void setIdTicket(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ticket_component.id_ticket</code>.
     */
    public Integer getIdTicket() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.ticket_component.id_component</code>.
     */
    public void setIdComponent(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ticket_component.id_component</code>.
     */
    public Integer getIdComponent() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.ticket_component.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ticket_component.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.ticket_component.cost_total</code>.
     */
    public void setCostTotal(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ticket_component.cost_total</code>.
     */
    public BigDecimal getCostTotal() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketComponentRecord
     */
    public TicketComponentRecord() {
        super(TicketComponent.TICKET_COMPONENT);
    }

    /**
     * Create a detached, initialised TicketComponentRecord
     */
    public TicketComponentRecord(Integer id, Integer idTicket, Integer idComponent, BigDecimal quantity, BigDecimal costTotal) {
        super(TicketComponent.TICKET_COMPONENT);

        setId(id);
        setIdTicket(idTicket);
        setIdComponent(idComponent);
        setQuantity(quantity);
        setCostTotal(costTotal);
        resetChangedOnNotNull();
    }
}
