/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import model.tables.Ticket;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TicketRecord extends UpdatableRecordImpl<TicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ticket.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ticket.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ticket.price_reparation</code>.
     */
    public void setPriceReparation(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ticket.price_reparation</code>.
     */
    public BigDecimal getPriceReparation() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.ticket.id_customer</code>.
     */
    public void setIdCustomer(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ticket.id_customer</code>.
     */
    public Integer getIdCustomer() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.ticket.id_model</code>.
     */
    public void setIdModel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ticket.id_model</code>.
     */
    public Integer getIdModel() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.ticket.id_engineer</code>.
     */
    public void setIdEngineer(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ticket.id_engineer</code>.
     */
    public Integer getIdEngineer() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.ticket.diagnostic</code>.
     */
    public void setDiagnostic(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ticket.diagnostic</code>.
     */
    public String getDiagnostic() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.ticket.id_ticket_state</code>.
     */
    public void setIdTicketState(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ticket.id_ticket_state</code>.
     */
    public Integer getIdTicketState() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.ticket.date_start</code>.
     */
    public void setDateStart(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.ticket.date_start</code>.
     */
    public LocalDateTime getDateStart() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.ticket.date_end</code>.
     */
    public void setDateEnd(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.ticket.date_end</code>.
     */
    public LocalDateTime getDateEnd() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketRecord
     */
    public TicketRecord() {
        super(Ticket.TICKET);
    }

    /**
     * Create a detached, initialised TicketRecord
     */
    public TicketRecord(Integer id, BigDecimal priceReparation, Integer idCustomer, Integer idModel, Integer idEngineer, String diagnostic, Integer idTicketState, LocalDateTime dateStart, LocalDateTime dateEnd) {
        super(Ticket.TICKET);

        setId(id);
        setPriceReparation(priceReparation);
        setIdCustomer(idCustomer);
        setIdModel(idModel);
        setIdEngineer(idEngineer);
        setDiagnostic(diagnostic);
        setIdTicketState(idTicketState);
        setDateStart(dateStart);
        setDateEnd(dateEnd);
        resetChangedOnNotNull();
    }
}
