/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDate;

import model.tables.VEngineerCommission;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VEngineerCommissionRecord extends TableRecordImpl<VEngineerCommissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_engineer_commission.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_engineer_commission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_engineer_commission.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_engineer_commission.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_engineer_commission.telephone</code>.
     */
    public void setTelephone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_engineer_commission.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_engineer_commission.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_engineer_commission.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_engineer_commission.address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_engineer_commission.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_engineer_commission.date</code>.
     */
    public void setDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_engineer_commission.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.v_engineer_commission.commission</code>.
     */
    public void setCommission(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_engineer_commission.commission</code>.
     */
    public Double getCommission() {
        return (Double) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VEngineerCommissionRecord
     */
    public VEngineerCommissionRecord() {
        super(VEngineerCommission.V_ENGINEER_COMMISSION);
    }

    /**
     * Create a detached, initialised VEngineerCommissionRecord
     */
    public VEngineerCommissionRecord(Integer id, String name, String telephone, String email, String address, LocalDate date, Double commission) {
        super(VEngineerCommission.V_ENGINEER_COMMISSION);

        setId(id);
        setName(name);
        setTelephone(telephone);
        setEmail(email);
        setAddress(address);
        setDate(date);
        setCommission(commission);
        resetChangedOnNotNull();
    }
}
