/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import model.tables.VLabelEntryComponent;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelEntryComponentRecord extends TableRecordImpl<VLabelEntryComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_label_entry_component.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_label_entry_component.datetime</code>.
     */
    public void setDatetime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.v_label_entry_component.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.v_label_entry_component.cost_unit</code>.
     */
    public void setCostUnit(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.cost_unit</code>.
     */
    public BigDecimal getCostUnit() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.v_label_entry_component.id_component</code>.
     */
    public void setIdComponent(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.id_component</code>.
     */
    public Integer getIdComponent() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.v_label_entry_component.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>public.v_label_entry_component.id_component_category</code>.
     */
    public void setIdComponentCategory(Integer value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.v_label_entry_component.id_component_category</code>.
     */
    public Integer getIdComponentCategory() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>public.v_label_entry_component.component_category</code>.
     */
    public void setComponentCategory(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.v_label_entry_component.component_category</code>.
     */
    public String getComponentCategory() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_label_entry_component.id_model_category</code>.
     */
    public void setIdModelCategory(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.id_model_category</code>.
     */
    public Integer getIdModelCategory() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.v_label_entry_component.model_category</code>.
     */
    public void setModelCategory(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.model_category</code>.
     */
    public String getModelCategory() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.v_label_entry_component.id_brand</code>.
     */
    public void setIdBrand(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.id_brand</code>.
     */
    public Integer getIdBrand() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.v_label_entry_component.brand</code>.
     */
    public void setBrand(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.brand</code>.
     */
    public String getBrand() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.v_label_entry_component.description</code>.
     */
    public void setDescription(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.description</code>.
     */
    public String getDescription() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_label_entry_component.id_supplier</code>.
     */
    public void setIdSupplier(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.id_supplier</code>.
     */
    public Integer getIdSupplier() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.v_label_entry_component.name</code>.
     */
    public void setName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.name</code>.
     */
    public String getName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_label_entry_component.telephone</code>.
     */
    public void setTelephone(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.v_label_entry_component.email</code>.
     */
    public void setEmail(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.email</code>.
     */
    public String getEmail() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.v_label_entry_component.address</code>.
     */
    public void setAddress(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_label_entry_component.address</code>.
     */
    public String getAddress() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VLabelEntryComponentRecord
     */
    public VLabelEntryComponentRecord() {
        super(VLabelEntryComponent.V_LABEL_ENTRY_COMPONENT);
    }

    /**
     * Create a detached, initialised VLabelEntryComponentRecord
     */
    public VLabelEntryComponentRecord(Integer id, LocalDateTime datetime, BigDecimal quantity, BigDecimal costUnit, Integer idComponent, String serialNumber, Integer idComponentCategory, String componentCategory, Integer idModelCategory, String modelCategory, Integer idBrand, String brand, String description, Integer idSupplier, String name, String telephone, String email, String address) {
        super(VLabelEntryComponent.V_LABEL_ENTRY_COMPONENT);

        setId(id);
        setDatetime(datetime);
        setQuantity(quantity);
        setCostUnit(costUnit);
        setIdComponent(idComponent);
        setSerialNumber(serialNumber);
        setIdComponentCategory(idComponentCategory);
        setComponentCategory(componentCategory);
        setIdModelCategory(idModelCategory);
        setModelCategory(modelCategory);
        setIdBrand(idBrand);
        setBrand(brand);
        setDescription(description);
        setIdSupplier(idSupplier);
        setName(name);
        setTelephone(telephone);
        setEmail(email);
        setAddress(address);
        resetChangedOnNotNull();
    }
}
