/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDate;

import model.tables.VLabelRecommendationComponent;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelRecommendationComponentRecord extends TableRecordImpl<VLabelRecommendationComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.v_label_recommendation_component.date_start</code>.
     */
    public void setDateStart(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.v_label_recommendation_component.date_start</code>.
     */
    public LocalDate getDateStart() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>public.v_label_recommendation_component.date_end</code>.
     */
    public void setDateEnd(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_label_recommendation_component.date_end</code>.
     */
    public LocalDate getDateEnd() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.v_label_recommendation_component.id</code>.
     */
    public void setId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_label_recommendation_component.id</code>.
     */
    public Integer getId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>public.v_label_recommendation_component.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.v_label_recommendation_component.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.v_label_recommendation_component.id_component_category</code>.
     */
    public void setIdComponentCategory(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.v_label_recommendation_component.id_component_category</code>.
     */
    public Integer getIdComponentCategory() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>public.v_label_recommendation_component.component_category</code>.
     */
    public void setComponentCategory(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.v_label_recommendation_component.component_category</code>.
     */
    public String getComponentCategory() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>public.v_label_recommendation_component.id_model_category</code>.
     */
    public void setIdModelCategory(Integer value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.v_label_recommendation_component.id_model_category</code>.
     */
    public Integer getIdModelCategory() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>public.v_label_recommendation_component.model_category</code>.
     */
    public void setModelCategory(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.v_label_recommendation_component.model_category</code>.
     */
    public String getModelCategory() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_label_recommendation_component.id_brand</code>.
     */
    public void setIdBrand(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_label_recommendation_component.id_brand</code>.
     */
    public Integer getIdBrand() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.v_label_recommendation_component.brand</code>.
     */
    public void setBrand(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_label_recommendation_component.brand</code>.
     */
    public String getBrand() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>public.v_label_recommendation_component.description</code>.
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>public.v_label_recommendation_component.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VLabelRecommendationComponentRecord
     */
    public VLabelRecommendationComponentRecord() {
        super(VLabelRecommendationComponent.V_LABEL_RECOMMENDATION_COMPONENT);
    }

    /**
     * Create a detached, initialised VLabelRecommendationComponentRecord
     */
    public VLabelRecommendationComponentRecord(LocalDate dateStart, LocalDate dateEnd, Integer id, String serialNumber, Integer idComponentCategory, String componentCategory, Integer idModelCategory, String modelCategory, Integer idBrand, String brand, String description) {
        super(VLabelRecommendationComponent.V_LABEL_RECOMMENDATION_COMPONENT);

        setDateStart(dateStart);
        setDateEnd(dateEnd);
        setId(id);
        setSerialNumber(serialNumber);
        setIdComponentCategory(idComponentCategory);
        setComponentCategory(componentCategory);
        setIdModelCategory(idModelCategory);
        setModelCategory(modelCategory);
        setIdBrand(idBrand);
        setBrand(brand);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
