/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import model.tables.VLabelModel;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelModelRecord extends TableRecordImpl<VLabelModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_label_model.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_label_model.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_label_model.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_label_model.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_label_model.id_model_category</code>.
     */
    public void setIdModelCategory(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_label_model.id_model_category</code>.
     */
    public Integer getIdModelCategory() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.v_label_model.model_category</code>.
     */
    public void setModelCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_label_model.model_category</code>.
     */
    public String getModelCategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_label_model.id_brand</code>.
     */
    public void setIdBrand(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_label_model.id_brand</code>.
     */
    public Integer getIdBrand() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.v_label_model.brand</code>.
     */
    public void setBrand(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_label_model.brand</code>.
     */
    public String getBrand() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_label_model.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_label_model.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VLabelModelRecord
     */
    public VLabelModelRecord() {
        super(VLabelModel.V_LABEL_MODEL);
    }

    /**
     * Create a detached, initialised VLabelModelRecord
     */
    public VLabelModelRecord(Integer id, String serialNumber, Integer idModelCategory, String modelCategory, Integer idBrand, String brand, String description) {
        super(VLabelModel.V_LABEL_MODEL);

        setId(id);
        setSerialNumber(serialNumber);
        setIdModelCategory(idModelCategory);
        setModelCategory(modelCategory);
        setIdBrand(idBrand);
        setBrand(brand);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
