/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDate;

import model.tables.VLabelReparation;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelReparationRecord extends TableRecordImpl<VLabelReparationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_label_reparation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_label_reparation.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.v_label_reparation.price</code>.
     */
    public void setPrice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.price</code>.
     */
    public Double getPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.v_label_reparation.id_model</code>.
     */
    public void setIdModel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.id_model</code>.
     */
    public Integer getIdModel() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.v_label_reparation.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_label_reparation.id_model_category</code>.
     */
    public void setIdModelCategory(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.id_model_category</code>.
     */
    public Integer getIdModelCategory() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.v_label_reparation.model_category</code>.
     */
    public void setModelCategory(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.model_category</code>.
     */
    public String getModelCategory() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_label_reparation.id_brand</code>.
     */
    public void setIdBrand(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.id_brand</code>.
     */
    public Integer getIdBrand() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.v_label_reparation.brand</code>.
     */
    public void setBrand(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.brand</code>.
     */
    public String getBrand() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_label_reparation.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_label_reparation.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VLabelReparationRecord
     */
    public VLabelReparationRecord() {
        super(VLabelReparation.V_LABEL_REPARATION);
    }

    /**
     * Create a detached, initialised VLabelReparationRecord
     */
    public VLabelReparationRecord(Integer id, LocalDate date, Double price, Integer idModel, String serialNumber, Integer idModelCategory, String modelCategory, Integer idBrand, String brand, String description) {
        super(VLabelReparation.V_LABEL_REPARATION);

        setId(id);
        setDate(date);
        setPrice(price);
        setIdModel(idModel);
        setSerialNumber(serialNumber);
        setIdModelCategory(idModelCategory);
        setModelCategory(modelCategory);
        setIdBrand(idBrand);
        setBrand(brand);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
