/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.math.BigDecimal;

import model.tables.VLabelMvtStockComponent;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelMvtStockComponentRecord extends TableRecordImpl<VLabelMvtStockComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_label_mvt_stock_component.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_stock_component.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_label_mvt_stock_component.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_stock_component.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.v_label_mvt_stock_component.cost_unit</code>.
     */
    public void setCostUnit(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_stock_component.cost_unit</code>.
     */
    public BigDecimal getCostUnit() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.v_label_mvt_stock_component.id_component</code>.
     */
    public void setIdComponent(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_stock_component.id_component</code>.
     */
    public Integer getIdComponent() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.v_label_mvt_stock_component.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_stock_component.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>public.v_label_mvt_stock_component.id_component_category</code>.
     */
    public void setIdComponentCategory(Integer value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.v_label_mvt_stock_component.id_component_category</code>.
     */
    public Integer getIdComponentCategory() {
        return (Integer) get(5);
    }

    /**
     * Setter for
     * <code>public.v_label_mvt_stock_component.component_category</code>.
     */
    public void setComponentCategory(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.v_label_mvt_stock_component.component_category</code>.
     */
    public String getComponentCategory() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>public.v_label_mvt_stock_component.id_model_category</code>.
     */
    public void setIdModelCategory(Integer value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.v_label_mvt_stock_component.id_model_category</code>.
     */
    public Integer getIdModelCategory() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>public.v_label_mvt_stock_component.model_category</code>.
     */
    public void setModelCategory(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>public.v_label_mvt_stock_component.model_category</code>.
     */
    public String getModelCategory() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_label_mvt_stock_component.id_brand</code>.
     */
    public void setIdBrand(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_stock_component.id_brand</code>.
     */
    public Integer getIdBrand() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.v_label_mvt_stock_component.brand</code>.
     */
    public void setBrand(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_stock_component.brand</code>.
     */
    public String getBrand() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.v_label_mvt_stock_component.description</code>.
     */
    public void setDescription(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_stock_component.description</code>.
     */
    public String getDescription() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VLabelMvtStockComponentRecord
     */
    public VLabelMvtStockComponentRecord() {
        super(VLabelMvtStockComponent.V_LABEL_MVT_STOCK_COMPONENT);
    }

    /**
     * Create a detached, initialised VLabelMvtStockComponentRecord
     */
    public VLabelMvtStockComponentRecord(Integer id, BigDecimal quantity, BigDecimal costUnit, Integer idComponent, String serialNumber, Integer idComponentCategory, String componentCategory, Integer idModelCategory, String modelCategory, Integer idBrand, String brand, String description) {
        super(VLabelMvtStockComponent.V_LABEL_MVT_STOCK_COMPONENT);

        setId(id);
        setQuantity(quantity);
        setCostUnit(costUnit);
        setIdComponent(idComponent);
        setSerialNumber(serialNumber);
        setIdComponentCategory(idComponentCategory);
        setComponentCategory(componentCategory);
        setIdModelCategory(idModelCategory);
        setModelCategory(modelCategory);
        setIdBrand(idBrand);
        setBrand(brand);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
