/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDate;

import model.tables.VLabelReparationFeedback;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelReparationFeedbackRecord extends TableRecordImpl<VLabelReparationFeedbackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_label_reparation_feedback.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.id_customer</code>.
     */
    public void setIdCustomer(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.id_customer</code>.
     */
    public Integer getIdCustomer() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.id_reparation</code>.
     */
    public void setIdReparation(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.id_reparation</code>.
     */
    public Integer getIdReparation() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.date_start</code>.
     */
    public void setDateStart(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.date_start</code>.
     */
    public LocalDate getDateStart() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.price</code>.
     */
    public void setPrice(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.price</code>.
     */
    public Double getPrice() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.id_model</code>.
     */
    public void setIdModel(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.id_model</code>.
     */
    public Integer getIdModel() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>public.v_label_reparation_feedback.id_model_category</code>.
     */
    public void setIdModelCategory(Integer value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.v_label_reparation_feedback.id_model_category</code>.
     */
    public Integer getIdModelCategory() {
        return (Integer) get(9);
    }

    /**
     * Setter for
     * <code>public.v_label_reparation_feedback.model_category</code>.
     */
    public void setModelCategory(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>public.v_label_reparation_feedback.model_category</code>.
     */
    public String getModelCategory() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.id_brand</code>.
     */
    public void setIdBrand(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.id_brand</code>.
     */
    public Integer getIdBrand() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.brand</code>.
     */
    public void setBrand(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.brand</code>.
     */
    public String getBrand() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_label_reparation_feedback.description</code>.
     */
    public void setDescription(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_label_reparation_feedback.description</code>.
     */
    public String getDescription() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VLabelReparationFeedbackRecord
     */
    public VLabelReparationFeedbackRecord() {
        super(VLabelReparationFeedback.V_LABEL_REPARATION_FEEDBACK);
    }

    /**
     * Create a detached, initialised VLabelReparationFeedbackRecord
     */
    public VLabelReparationFeedbackRecord(Integer id, LocalDate date, Integer idCustomer, Integer idReparation, String name, LocalDate dateStart, Double price, Integer idModel, String serialNumber, Integer idModelCategory, String modelCategory, Integer idBrand, String brand, String description) {
        super(VLabelReparationFeedback.V_LABEL_REPARATION_FEEDBACK);

        setId(id);
        setDate(date);
        setIdCustomer(idCustomer);
        setIdReparation(idReparation);
        setName(name);
        setDateStart(dateStart);
        setPrice(price);
        setIdModel(idModel);
        setSerialNumber(serialNumber);
        setIdModelCategory(idModelCategory);
        setModelCategory(modelCategory);
        setIdBrand(idBrand);
        setBrand(brand);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
