/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import model.tables.VLabelMvtTicketState;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelMvtTicketStateRecord extends TableRecordImpl<VLabelMvtTicketStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.datetime</code>.
     */
    public void setDatetime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.id_ticket</code>.
     */
    public void setIdTicket(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.id_ticket</code>.
     */
    public Integer getIdTicket() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.price_reparation</code>.
     */
    public void setPriceReparation(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.price_reparation</code>.
     */
    public BigDecimal getPriceReparation() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.id_customer</code>.
     */
    public void setIdCustomer(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.id_customer</code>.
     */
    public Integer getIdCustomer() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.telephone</code>.
     */
    public void setTelephone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.email</code>.
     */
    public void setEmail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.email</code>.
     */
    public String getEmail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.address</code>.
     */
    public void setAddress(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.address</code>.
     */
    public String getAddress() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.id_model</code>.
     */
    public void setIdModel(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.id_model</code>.
     */
    public Integer getIdModel() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>public.v_label_mvt_ticket_state.id_model_category</code>.
     */
    public void setIdModelCategory(Integer value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>public.v_label_mvt_ticket_state.id_model_category</code>.
     */
    public Integer getIdModelCategory() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.model_category</code>.
     */
    public void setModelCategory(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.model_category</code>.
     */
    public String getModelCategory() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.id_brand</code>.
     */
    public void setIdBrand(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.id_brand</code>.
     */
    public Integer getIdBrand() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.brand</code>.
     */
    public void setBrand(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.brand</code>.
     */
    public String getBrand() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.description</code>.
     */
    public void setDescription(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.description</code>.
     */
    public String getDescription() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.diagnostic</code>.
     */
    public void setDiagnostic(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.diagnostic</code>.
     */
    public String getDiagnostic() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.id_ticket_state</code>.
     */
    public void setIdTicketState(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.id_ticket_state</code>.
     */
    public Integer getIdTicketState() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.ticket_state</code>.
     */
    public void setTicketState(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.ticket_state</code>.
     */
    public String getTicketState() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.date_start</code>.
     */
    public void setDateStart(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.date_start</code>.
     */
    public LocalDateTime getDateStart() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>public.v_label_mvt_ticket_state.date_end</code>.
     */
    public void setDateEnd(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_label_mvt_ticket_state.date_end</code>.
     */
    public LocalDateTime getDateEnd() {
        return (LocalDateTime) get(20);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VLabelMvtTicketStateRecord
     */
    public VLabelMvtTicketStateRecord() {
        super(VLabelMvtTicketState.V_LABEL_MVT_TICKET_STATE);
    }

    /**
     * Create a detached, initialised VLabelMvtTicketStateRecord
     */
    public VLabelMvtTicketStateRecord(Integer id, LocalDateTime datetime, Integer idTicket, BigDecimal priceReparation, Integer idCustomer, String name, String telephone, String email, String address, Integer idModel, String serialNumber, Integer idModelCategory, String modelCategory, Integer idBrand, String brand, String description, String diagnostic, Integer idTicketState, String ticketState, LocalDateTime dateStart, LocalDateTime dateEnd) {
        super(VLabelMvtTicketState.V_LABEL_MVT_TICKET_STATE);

        setId(id);
        setDatetime(datetime);
        setIdTicket(idTicket);
        setPriceReparation(priceReparation);
        setIdCustomer(idCustomer);
        setName(name);
        setTelephone(telephone);
        setEmail(email);
        setAddress(address);
        setIdModel(idModel);
        setSerialNumber(serialNumber);
        setIdModelCategory(idModelCategory);
        setModelCategory(modelCategory);
        setIdBrand(idBrand);
        setBrand(brand);
        setDescription(description);
        setDiagnostic(diagnostic);
        setIdTicketState(idTicketState);
        setTicketState(ticketState);
        setDateStart(dateStart);
        setDateEnd(dateEnd);
        resetChangedOnNotNull();
    }
}
