/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDateTime;

import model.tables.VStateMvtTicketState;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VStateMvtTicketStateRecord extends TableRecordImpl<VStateMvtTicketStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_state_mvt_ticket_state.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_state_mvt_ticket_state.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_state_mvt_ticket_state.datetime</code>.
     */
    public void setDatetime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_state_mvt_ticket_state.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.v_state_mvt_ticket_state.id_ticket</code>.
     */
    public void setIdTicket(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_state_mvt_ticket_state.id_ticket</code>.
     */
    public Integer getIdTicket() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.v_state_mvt_ticket_state.id_ticket_state</code>.
     */
    public void setIdTicketState(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_state_mvt_ticket_state.id_ticket_state</code>.
     */
    public Integer getIdTicketState() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VStateMvtTicketStateRecord
     */
    public VStateMvtTicketStateRecord() {
        super(VStateMvtTicketState.V_STATE_MVT_TICKET_STATE);
    }

    /**
     * Create a detached, initialised VStateMvtTicketStateRecord
     */
    public VStateMvtTicketStateRecord(Integer id, LocalDateTime datetime, Integer idTicket, Integer idTicketState) {
        super(VStateMvtTicketState.V_STATE_MVT_TICKET_STATE);

        setId(id);
        setDatetime(datetime);
        setIdTicket(idTicket);
        setIdTicketState(idTicketState);
        resetChangedOnNotNull();
    }
}
