/*
 * This file is generated by jOOQ.
 */
package model.routines;


import model.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PStateMvtTicketState extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>public.p_state_mvt_ticket_state.id_ticket_param</code>.
     */
    public static final Parameter<Integer> ID_TICKET_PARAM = Internal.createParameter("id_ticket_param", SQLDataType.INTEGER, false, false);

    /**
     * The parameter
     * <code>public.p_state_mvt_ticket_state.id_ticket_status_output</code>.
     */
    public static final Parameter<Integer> ID_TICKET_STATUS_OUTPUT = Internal.createParameter("id_ticket_status_output", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public PStateMvtTicketState() {
        super("p_state_mvt_ticket_state", Public.PUBLIC);

        addInParameter(ID_TICKET_PARAM);
        addOutParameter(ID_TICKET_STATUS_OUTPUT);
        setSQLUsable(false);
    }

    /**
     * Set the <code>id_ticket_param</code> parameter IN value to the routine
     */
    public void setIdTicketParam(Integer value) {
        setValue(ID_TICKET_PARAM, value);
    }

    /**
     * Get the <code>id_ticket_status_output</code> parameter OUT value from the
     * routine
     */
    public Integer getIdTicketStatusOutput() {
        return get(ID_TICKET_STATUS_OUTPUT);
    }
}
